#!/bin/sh
_github_latest_release() {
  [ -z "$4" ] && {
    get_latest_${1}_version
    return
  }
  local _field=${4#.}
  curl $conf_curl_flags -sL https://api.github.com/repos/$2/$3/releases/latest | grep -m1 "\"$_field\"" | sed 's/.*"[^"]*": *"\([^"]*\)".*/\1/'
}
_github_fetch() {
  local download_url=$(curl $conf_curl_flags -s https://api.github.com/repos/$1/$2/releases/latest | jq -r "$3")
  [ -z "$download_url" ] && {
    log_warn "no matching artifact found"
    return 1
  }
  _download_fetch "$download_url" $4-$5
}
_github_install_latest() {
  local function_name=$(printf '%s' $1 | tr '-' '_')
  local latest_version=$(_github_latest_release "$function_name" "$2" "$3" "$4")
  local installed_version=$(get_installed_${function_name}_version)
  [ "$installed_version" = "$latest_version" ] && {
    log_detail "$1 is already installed and up-to-date"
    return
  }
  if [ -z "$installed_version" ]; then
    log_detail "installing $1"
  else
    log_detail "updating $1"
  fi
  _github_fetch "$2" "$3" "$5" "$6" "$latest_version" || return
  [ -z "$7" ] && {
    log_info "calling install_$function_name"
    install_$function_name
    return
  }
  _install_file_chmod=755 _download_install_file "$TARGET_APP_PLATFORM_BIN_PATH/$7"
}
_download_fetch() {
  mkdir -p "$TARGET_APP_PLATFORM_CACHE_PATH"
  local _cached_filename
  if [ $# -gt 1 ]; then
    _cached_filename="$2"
  else
    _cached_filename=$(basename "$1" | sed -e 's/?.*$//')
  fi
  download_file="$TARGET_APP_PLATFORM_CACHE_PATH/$_cached_filename"
  [ -z "$no_cache" ] && {
    [ -s "$download_file" ] && {
      log_detail "$1 already downloaded to: $download_file"
      return
    }
  }
  if [ -z "$download_disabled" ]; then
    log_info "downloading $1 -> $download_file"
    curl $conf_curl_flags -f -o "$download_file" -sL "$1"
    local _curl_status=$?
    if [ "$_curl_status" -ne 0 ]; then
      rm -f "$download_file"
      log_warn "failed to download ($_curl_status): $1"
      return $_curl_status
    fi
  else
    _stdin_continue_if "Please manually download: $1 and place it in $download_file" "Y/n"
  fi
}
_download_install_file() {
  warn_on_error=1 validation_require "$1" "1 (_download_install_file) target filename" || return 1
  warn_on_error=1 validation_require "$download_file" "download_file" || return 1
  : ${_install_file_chmod:=444}
  log_info "installing $download_file -> $1"
  if [ "${INSTALL_TARGET:-USER}" = "SYSTEM" ]; then
    sudo_run mkdir -p $(dirname $1)
    sudo_run cp "$download_file" $1
    sudo_run chmod $_install_file_chmod $1
  else
    mkdir -p $(dirname $1)
    cp "$download_file" $1
    chmod $_install_file_chmod $1
  fi
  unset download_file
  [ -e $1 ] || {
    log_warn "failed to install file to: $1"
    return 1
  }
  _install_record_path "$1"
}
_download_verify() {
  shasum -a 512 -c $1 >/dev/null 2>&1
}
: ${conf_dev_java_timo_a_lomboker_jdk:=java}
: ${conf_dev_java_timo_a_lomboker_version:=0.0.0}
: ${conf_dev_java_timo_a_lomboker_jar_NAME:=lomboker-$conf_dev_java_timo_a_lomboker_version.jar}
if [ -n "$TARGET_APP_PATH" ]; then
  : ${conf_dev_java_timo_a_lomboker_jar:=$TARGET_APP_PATH/tools/$conf_dev_java_timo_a_lomboker_jar_NAME}
else
  : ${conf_dev_java_timo_a_lomboker_jar:=$APP_PATH/tools/$conf_dev_java_timo_a_lomboker_jar_NAME}
fi
get_installed_timo_a_lomboker_version() {
  [ ! -e $TARGET_APP_PATH/tools/timo-a-lomboker.jar ] && return
  printf 'v'
  java -jar $TARGET_APP_PATH/tools/timo-a-lomboker.jar version | cut -d' ' -f2
}
install_timo_a_lomboker() {
  _download_install_file $TARGET_APP_PATH/tools/timo-a-lomboker.jar
}
_github_install_latest timo-a-lomboker timo-a lomboker '.tag_name' \
    ".assets[] | select(.name | test(\"lomboker-.*.jar\")) | .browser_download_url" \
    timo-a-lomboker.jar
