#!/bin/sh
_beep_beep() {
  [ "$EUID" -eq 0 ] && return 1
  beep $1 &
}
sudo_precmd() {
  _beep_beep "$conf_log_sudo_beep_tone"
}
_cfg_validate_required() {
  [ -n "$REQUIRED_APP_CONF" ] && {
    for required_app_conf_element in $REQUIRED_APP_CONF; do
      _environment_variable_is_set $required_app_conf_element || {
        log_warn "required configuration unset: $required_app_conf_element"
        missing_required_conf=1
      }
    done
    if [ -n "$missing_required_conf" ]; then
      exit_with_error "required configuration is missing, please refer to above error(s)"
    fi
  }
}
_environment_variable_is_set() {
  set | grep -cqm1 "^$1=.*$"
}
_environment_dump() {
  [ "$conf_log_level" -gt 0 ] && return
  set | sort
}
exec_call() {
  local _function_name=$1
  shift
  type $_function_name >/dev/null 2>&1 || {
    log_debug "${_function_name} does not exist"
    return 255
  }
  $_function_name "$@"
}
exec_wrap() {
  if [ -n "$exec_attempts" ]; then
    local _attempt=1
    while [ $_attempt -le $exec_attempts ]; do
      [ $_attempt -gt 1 ] && [ -n "$exec_delay" ] && sleep $exec_delay
      warn_on_error=1 _exec_do_exec "$@" && return
      _attempt=$(($_attempt + 1))
    done
    exit_with_error "failed after $_attempt attempts: $*"
  fi
  _exec_do_exec "$@"
}
_exec_do_exec() {
  local _successful_exit_status=0
  if [ -n "$successful_exit_status" ]; then
    _successful_exit_status=$successful_exit_status
    unset successful_exit_status
  fi
  log_info "$*"
  local _exit_status
  if [ -z "$dry_run" ]; then
    if [ -z "$log_logfile" ]; then
      "$@"
      _exit_status=$?
    else
      "$@" 2>&1 | sed -u 's/^/    /' | tee -a "$log_logfile"
      _exit_status=$?
    fi
  else
    log_warn "using dry run status: $dry_run"
    _exit_status=$dry_run
  fi
  if [ $_exit_status -ne $_successful_exit_status ]; then
    if [ -n "$on_failure" ]; then
      $on_failure
      return
    fi
    if [ -z "$warn_on_error" ]; then
      exit_with_error "previous cmd failed: $* - $_exit_status"
    else
      unset warn_on_error
      log_warn "previous cmd failed: $* - $_exit_status"
      environment_file=$(_mktemp_mktemp error) _environment_dump
      return $_exit_status
    fi
  fi
}
exit_with_error() {
  [ -n "$exit_status" ] && return
  if [ $# -ge 2 ]; then
    exit_status=$2
  else
    exit_status=1
  fi
  [ -n "$3" ] && {
    _exit_print_line $3
  }
  exit_log_level=4
  exit_status_code="ERR"
  exit_color_code="$conf_log_c_err"
  exit_message="$1 ($exit_status)"
  exit_beep="$conf_log_beep_err"
  exit_defer _exit_log_app_exit
  exit_defer _environment_dump
  _exit_run_defers
  exit $exit_status
}
exit_with_success() {
  [ -n "$exit_status" ] && return
  exit_status=0
  exit_log_level=1
  exit_status_code="SCS"
  exit_color_code="$conf_log_c_scs"
  exit_message="$1"
  [ -z "$exit_message" ] && exit_message="success"
  exit_beep="$conf_log_beep_scs"
  exit_defer _alert_long_running_cmd
  exit_defer _exit_log_app_exit
  _exit_run_defers
  exit $exit_status
}
_exit_on_hup() {
  log_info "hup received"
}
_exit_on_int() {
  exit_with_error "interrupted" $? $1
}
_exit_on_quit() {
  exit_with_error "quit" $? $1
}
_exit_on_illegal() {
  exit_with_error "illegal instruction" $? $1
}
_exit_on_abort() {
  exit_with_error "abort" $? $1
}
_exit_on_alarm() {
  exit_with_error "alarm" $? $1
}
_exit_on_term() {
  exit_with_error "term" $? $1
}
_exit_print_line() {
  log_warn "unhandled error"
  local _exception_line
  _exception_line=$($GNU_SED -n "${1}p" $0)
  printf '  %s @ %s:%s\n' "$_exception_line" $0 $1
}
exit_defer() {
  log_debug "deferring: $*"
  if [ $# -gt 1 ]; then
    local _defer_with_args
    _defer_with_args=$(printf '%s' "$*" | sed -e 's/ /:/' -e 's/ /,/g')
    exit_defers="$_defer_with_args $exit_defers"
  else
    exit_defers="$1 $exit_defers"
  fi
}
exit_undefer() {
  log_debug "undeferring: $*"
  local _undefer_target
  if [ $# -gt 1 ]; then
    _undefer_target=$(printf '%s' "$*" | sed -e 's/ /:/' -e 's/ /,/g')
  else
    _undefer_target="$1"
  fi
  local _new_defers=""
  local _defer
  for _defer in $exit_defers; do
    if [ "$_defer" != "$_undefer_target" ]; then
      _new_defers="$_defer $_new_defers"
    fi
  done
  exit_defers=""
  for _defer in $_new_defers; do
    exit_defers="$_defer $exit_defers"
  done
}
_exit_run_defers() {
  [ -z "$exit_defers" ] && return 1
  for exit_defer in $exit_defers; do
    case "$exit_defer" in
    *:*)
      local _func_name=$(printf '%s' "$exit_defer" | cut -d':' -f1)
      local _args=$(printf '%s' "$exit_defer" | cut -d':' -f2 | tr ',' ' ')
      exec_call $_func_name $_args
      ;;
    *)
      exec_call $exit_defer
      ;;
    esac
  done
  unset exit_defers
}
_exit_log_app_exit() {
  [ "$exit_message" ] && {
    _exit_disable_beep
    log_print_log $exit_log_level "$exit_status_code" "$exit_color_code" "$exit_beep" "$exit_message"
  }
  log_app exit
  [ -n "$log_logfile" ] && [ -n "$optn_log_exit_cmd" ] && {
    $optn_log_exit_cmd -file $log_logfile
  }
}
_exit_disable_beep() {
  [ -z "$APPLICATION_START_TIME" ] && {
    unset exit_beep
    return
  }
  local _current_time=$(date +%s)
  local _timeout=$(($APPLICATION_START_TIME + $conf_log_beep_timeout))
  [ $_current_time -ge $_timeout ] && return
  unset exit_beep
}
_help_print() {
  if [ -e $2 ]; then
    log_info "$1:"
    cat $2
    printf '\n'
  fi
}
_help_print_and_exit() {
  _help_print 'system-wide options' $APP_PLATFORM_PATH/install/help/default
  if [ "$APPLICATION_NAME" != "install" ]; then
    _help_print $APPLICATION_NAME $APP_PLATFORM_PATH/$APPLICATION_NAME/help/default
    _help_print "$APPLICATION_NAME/$APPLICATION_CMD" $APP_PLATFORM_PATH/$APPLICATION_NAME/help/$APPLICATION_CMD
  fi
  exit 0
}
file_require() {
  local _filename=$1
  local _message=$2
  validation_require "$_filename" "filename file_require"
  [ -e "$_filename" ] && return
  [ -z "$warn_on_error" ] && exit_with_error "file: $_filename does not exist | $_message"
  log_warn "file: $_filename does not exist | $_message"
  return 1
}
_file_has_contents() {
  local _filename=$1
  file_require "$_filename" "_file_has_contents:$_filename"
  [ $(wc -l <"$_filename") -gt 0 ]
}
_include_optional() {
  inc_err=0
  for inc_file in "$@"; do
    case "$inc_file" in
    */*)
      ;;
    *)
      inc_file="${APP_PLATFORM_CONFIG_PATH}/$inc_file"
      ;;
    esac
    if [ -f "$inc_file" ] && . "$inc_file"; then
      :
    else
      inc_err=$(($inc_err + 1))
    fi
  done
  unset inc_file inc_dir _found
  [ "$inc_err" -eq 0 ]
}
log_to_console() {
  local _color=$1 _event_date_time=$2 _message=$3
  [ -n "$NON_INTERACTIVE" ] && [ -n "$NO_LOG_FILE" ] && {
    if [ "$conf_log_date_time_to_console" -eq 1 ]; then
      printf '%s - %s\n' "$_event_date_time" "$_message" >&2
    else
      printf '%s\n' "$_message" >&$console_log_fd
    fi
    return
  }
  if [ "$conf_log_date_time_to_console" -eq 1 ]; then
    printf '\033[%sm%s - %s\033[0m\n' "$_color" "$_event_date_time" "$_message" >&2
  else
    printf '\033[%sm%s\033[0m\n' "$_color" "$_message" >&$console_log_fd
  fi
}
log_add_context() {
  [ -z "$1" ] && return 1
  local context_to_add="$1"
  case "$context_to_add" in
  *:*)
    log_debug "replacing : with |"
    context_to_add=$(printf '%s' "$context_to_add" | tr ':' '|')
    ;;
  esac
  if [ -z "$logging_context" ]; then
    logging_context="$context_to_add"
  else
    logging_context="${logging_context}:$context_to_add"
  fi
}
log_remove_context() {
  [ -z "$logging_context" ] && return 1
  case $logging_context in
  *:*)
    logging_context=$(printf '%s' "$logging_context" | sed -e 's/\:[a-zA-Z0-9/@\. _-]*$//')
    ;;
  *)
    unset logging_context
    ;;
  esac
}
log_to_file() {
  [ -z "$log_logfile" ] && return 0
  [ -n "$NO_LOG_FILE" ] && return 1
  printf '%s %s %s\n' "$1" "$2" "$3" >>$log_logfile
}
_log_set_logfile() {
  [ -z "$1" ] && return
  [ -n "$NO_LOG_FILE" ] && return 1
  log_logfile="$(realpath -m $(dirname $1))/$(basename $1)"
  mkdir -p $(dirname $log_logfile)
  log_to_console "${conf_log_c_wrn}" "$(date '+%Y/%m/%d %H:%M:%S')" "writing logs to ${log_logfile}${log_msg}"
  if [ -z "${_log_saved_fds}" ]; then
    if [ "$console_log_fd" -le 2 ]; then
      exec 3>&1 4>&2
      console_log_fd=4
    fi
    _log_saved_fds=1
  fi
  exec >>"$log_logfile" 2>&1
}
log_warn() {
  log_print_log 3 WRN "${conf_log_c_wrn}" "${conf_log_beep_wrn}" "$1"
}
log_info() {
  log_print_log 2 INF "${conf_log_c_info}" "${conf_log_beep_info}" "$1"
}
log_detail() {
  log_print_log 2 DTL "${conf_log_c_detail}" "${conf_log_beep_detail}" "$1"
}
log_debug() {
  log_print_log 1 DBG "${conf_log_c_debug}" "${conf_log_beep_debug}" "($$) $1"
}
log_init() {
  [ -n "$log_logfile" ] && _log_set_logfile "$log_logfile"
  log_add_context "$APPLICATION_NAME"
  log_add_context "$APPLICATION_CMD"
  if [ -n "$add_log_context" ]; then
    log_add_context "$add_log_context"
    unset add_log_context
  fi
  log_enable_debug_mode
}
log_enable_debug_mode() {
  [ "$conf_log_level" -gt 0 ] && {
    set +x
    return
  }
  [ -z "$log_logfile" ] && {
    log_msg=" - DEBUG"
    _log_set_logfile "$(_mktemp_mktemp debug)" || return 1
  }
  set -x
}
log_print_log() {
  local _level=$1 _level_str=$2 _color=$3 _tone=$4 _message="$5"
  [ $_level -lt $conf_log_level ] && return 0
  [ -n "$logging_context" ] &&
    _message="${logging_context} - ${_message}"
  [ -n "$_tone" ] && [ $beep_enabled -eq 1 ] && _beep_beep "$_tone"
  local log_event_date_time="$(date '+%Y/%m/%d %H:%M:%S')"
  log_to_file "$_level_str" "$log_event_date_time" "$_message"
  log_to_console "$_color" "$log_event_date_time" "$_message"
  log_user_log "$_level_str" "$log_event_date_time" "$_message"
  [ -n "$log_syslog" ] && _syslog_syslog "$_message"
  return 0
}
log_app() {
  log_debug "$APPLICATION_NAME:$APPLICATION_CMD - $1 ($$)"
}
log_user_log() { :; }
_metadata_load() {
  [ -f $APP_PATH/.metadata ] && . $APP_PATH/.metadata && return 0
  [ -n "$HOME" ] && [ -f "$HOME/.local/walterjwhite/apps/$APPLICATION_NAME/.metadata" ] && . "$HOME/.local/walterjwhite/apps/$APPLICATION_NAME/.metadata"
}
_mktemp_mktemp() {
  local _suffix=$1
  [ -n "$_suffix" ] && _suffix=".$_suffix"
  mktemp -${_mktemp_options}t ${APPLICATION_NAME}.${APPLICATION_CMD}${_suffix}.XXXXXXXX
}
platform_is_supported() {
  local _supported_platforms="$1"
  local _platform
  [ -z "$_supported_platforms" ] && return 0
  for _platform in $_supported_platforms; do
    [ "$APP_PLATFORM_PLATFORM" = "$_platform" ] && return 0
  done
  exit_with_error "platform '$APP_PLATFORM_PLATFORM' is not supported; supported: $_supported_platforms"
}
processes_restrict_to_single_process() {
  _processes_has_other_instances && {
    exit_with_error "$APPLICATION_CMD is restricted to a single instance and another instance is running"
  }
  processes_setup_app_pipe
}
_processes_has_other_instances() {
  find $APPLICATION_CMD_DIR -maxdepth 1 -type p ! -name $$ 2>/dev/null | grep -qm1 '.'
}
processes_setup_app_pipe() {
  mkdir -p $APPLICATION_PIPE_DIR
  mkfifo $APPLICATION_PIPE
  exit_defer processes_cleanup_app_pipe
}
processes_cleanup_app_pipe() {
  rm -rf $APPLICATION_PIPE_DIR
}
_processes_is_backgrounded() {
  [ -n "$no_ps" ] && return 1
  case $(ps -o stat= -p $$) in
  *+*)
    return 1
    ;;
  esac
  return 0
}
_stdin_interactive_alert_if() {
  _stdin_is_interactive_alert_enabled && _interactive_alert "$@"
}
_stdin_is_interactive_alert_enabled() {
  [ -n "$optn_interactive_alert" ]
}
_stdin_continue_if() {
  unset _proceed
  _stdin_read_if "$1" _proceed "$2"
  if [ -z "$_proceed" ]; then
    _default=$(printf '%s' $2 | awk -F'/' {'print$1'})
    _proceed=$_default
  fi
  printf '%s' "$_proceed" | tr '[:lower:]' '[:upper:]' | $GNU_GREP -Pcqm1 '^Y$'
}
_stdin_read_if() {
  if [ $(set | grep -c "^$2=.*") -eq 1 ]; then
    log_debug "$2 is already set"
    return 1
  fi
  [ -n "$NON_INTERACTIVE" ] && exit_with_error "running in non-interactive mode and user input was requested: $@" 10
  log_print_log 9 STDI "$conf_log_c_stdin" "$conf_log_beep_stdin" "$1 $3"
  _stdin_interactive_alert_if $1 $3
  read -r $2
}
_syslog_syslog() {
  logger -i -t "$APPLICATION_NAME.$APPLICATION_CMD" "$1"
}
sudo_run() {
  [ $# -eq 0 ] && exit_with_error 'no arguments were provided to sudo_run'
  sudo_is_validation_required || {
    "$@"
    return
  }
  validation_require "$_SUDO_CMD" "sudo_cmd - $*"
  [ -z "$NON_INTERACTIVE" ] && {
    $_SUDO_CMD -n ls >/dev/null 2>&1 || sudo_precmd "$@"
  }
  $_SUDO_CMD $sudo_options "$@"
  local sudo_return_status=$?
  unset sudo_options
  return $sudo_return_status
}
sudo_is_validation_required() {
  [ -n "$sudo_user" ] && {
    [ "$sudo_user" = "$USER" ] && return 1
    sudo_options="$sudo_options -u $sudo_user"
    return 0
  }
  [ "$USER" = "root" ] && return 1
  return 0
}
sudo_ensure_root() {
  [ "$(id -u)" -eq 0 ] && return
  log_info "enter sudo password to run this program as root"
  sudo_run "$0" "$@"
  exit $?
}
sudo_ensure_not_root() {
  [ $(id -u) -ne 0 ] && return
  exit_with_error "$0 cannot be run as root"
}
sudo_ensure_non_root_user() {
  [ "$(id -u)" -ne 0 ] && return
  [ -z "$SUDO_USER" ] && exit_with_error "unable to determine non-root user"
  sudo_user=$SUDO_USER
  sudo_run "$0" "$@"
  exit $?
}
time_timeout() {
  local _timeout=$1
  shift
  local _message=$1
  shift
  local _timeout_units='s'
  if [ $(printf '%s' "$_timeout" | grep -c '[smhd]{1}') -gt 0 ]; then
    unset _timeout_units
  fi
  local _sudo
  [ -n "$sudo_required" ] || [ -n "$sudo_user" ] && _sudo=sudo_run
  $_sudo timeout $options $_timeout "$@" || {
    local _error_status=$?
    local _error_message="Other error"
    if [ $_error_status -eq 124 ]; then
      _error_message="Timed Out"
    fi
    [ $timeout_err_function ] && $timeout_err_function
    local timeout_error_msg="time_timeout: $_error_message: ${_timeout}${_timeout_units} - $_message ($_error_status): $_sudo timeout $options $_timeout $* ($USER)"
    [ $warn_on_error ] && {
      log_warn "$timeout_error_msg"
      return $_error_status
    }
    exit_with_error "$timeout_error_msg"
  }
}
wait_waitee_init() {
  [ -z "$WAIT_WAITEE" ] && return
  processes_setup_app_pipe
  log_warn "please use -w=$$ ($APPLICATION_CMD)"
  exit_defer wait_waitee_done
}
wait_waitee_done() {
  [ -z "$WAIT_WAITEE" ] && return
  [ -e $application_pipe ] || return
  log_info "$0 process completed, notifying ($exit_status)"
  printf '%s\n' "$exit_status" >$application_pipe
  log_info "$0 downstream process picked up"
}
wait_waiter() {
  local _upstream_application_pipe
  local _upstream_application_status
  local _upstream_status
  [ -z "$wait_waiter_pid" ] && return
  _upstream_application_pipe=$(find $APPLICATION_CONTEXT_GROUP -type p -name $wait_waiter_pid 2>/dev/null | head -1)
  [ -z "$_upstream_application_pipe" ] && exit_with_error "$wait_waiter_pid not found"
  [ ! -e $_upstream_application_pipe ] && {
    log_warn "$_upstream_application_pipe does not exist, did upstream start?"
    return
  }
  log_info "waiting for upstream to complete: $wait_waiter_pid"
  while :; do
    if [ ! -e $_upstream_application_pipe ]; then
      exit_with_error "upstream pipe no longer exists"
    fi
    _upstream_application_status=$(time_timeout $conf_wait_interval "wait_waiter:upstream" cat $_upstream_application_pipe 2>/dev/null)
    _upstream_status=$?
    if [ $_upstream_status -eq 0 ]; then
      if [ -z "$_upstream_application_status" ] || [ $_upstream_application_status -gt 0 ]; then
        exit_with_error "upstream exited with exit_with_error ($_upstream_application_status)"
      fi
      log_warn "upstream finished: $_upstream_application_pipe ($_upstream_status)"
      break
    fi
    log_detail "upstream is still running: $_upstream_application_pipe ($_upstream_status)"
    sleep 1
  done
}
validation_require() {
  [ -n "$1" ] && return
  [ -n "$warn_on_error" ] && {
    log_warn "$2 required $required_message" $3
    return 1
  }
  exit_with_error "$2 required $required_message" $3
}
_mail_send() {
  [ -n "$conf_log_mail_disabled" ] && {
    log_warn "mail is disabled"
    return 1
  }
  if [ $# -lt 3 ]; then
    log_warn "recipients[0], subject[1], message[2] is required - $# arguments provided"
    return 2
  fi
  local _recipients
  _recipients=$(printf '%s' "$1" | tr '|' ' ')
  shift
  local _subject
  _subject="$1"
  shift
  local _message
  _message="$1"
  shift
  printf '%s\n' "$_message" | mail -s "$_subject" $_recipients
}
_alert_alert() {
  local _recipients
  local _subject
  local _log_color
  case $exit_status in
  0)
    _log_color=$conf_log_c_scs
    ;;
  *)
    _log_color=$conf_log_c_err
    ;;
  esac
  log_print_log 5 ALRT "$_log_color" "$conf_log_beep_alrt" "$1"
  _recipients="$optn_log_alert_recipients"
  _subject="alert: $0 - $1"
  if [ -z "$_recipients" ]; then
    log_debug "recipients is empty, aborting"
    return 1
  fi
  _mail_send "$_recipients" "$_subject" "$2"
}
_alert_long_running_cmd() {
  [ -n "$optn_disable_long_running_cmd_notification" ] && return
  local _application_end_time=$(date +%s)
  local _application_runtime=$(($_application_end_time - $APPLICATION_START_TIME))
  [ $_application_runtime -lt $conf_log_long_running_cmd ] && return
  local _subject="$logging_context - $exit_message - ($exit_status)"
  local _message=""
  if [ -n "$log_logfile" ]; then
    _message=$(tail -$conf_log_long_running_cmd_lines $log_logfile)
  fi
  _alert_alert "$_subject" "$_message"
}
_chroot_init() {
  :
}
_run_parallel() {
  _is_run_parallel && {
    _run_parallel_do
    return
  }
  _run_sequential
}
_run_parallel_do() {
  _parallel=0
  _patches_patches kernel &
  _kernel_pid=$!
  _patches_patches zfs &
  _zfs_pid=$!
  _patches_patches download &
  _download_pid=$!
  exit_defer kill -9 $_kernel_pid $_zfs_pid $_download_pid
}
_run_sequential() {
  _patches_patches kernel zfs download
}
_run_parallel_wait() {
  [ -z "$_parallel" ] && return
  log_info "waiting for Downloads ($_download_pid) Kernel ($_kernel_pid) ZFS ($_zfs_pid)"
  wait $_download_pid $_kernel_pid $_zfs_pid
  unset _download_pid _kernel_pid _zfs_pid _parallel
}
_is_run_parallel() {
  return 0
}
_chroot_timezone() {
  ln -sf /usr/share/zoneinfo/$os_installer_system_timezone /etc/localtime
}
_configure_configure() {
  log_info "configuring system"
  cd $conf_os_installer_system_workspace
  _configure_system
  _configure_patches
}
_configure_system() {
  log_info "configuring system/conf"
  [ -e system/conf ] && {
    _import_conf system/conf
  }
  local import_file
  for import_file in $(find imports -type f -path '*/system/conf'); do
    _import_conf "$import_file"
  done
}
_import_conf() {
  log_debug "importing $1"
  . $1
}
_configure_patches() {
  log_debug "configuring patches - $PWD"
  local configuration_script patch_path
  for configuration_script in $(find patches imports -type f -path '*.patch/configure'); do
    patch_path=$(dirname $configuration_script)
    log_debug "evaluating $patch_path"
    . $configuration_script || {
      log_debug "$configuration_script [$?], disabling patch"
      rm -rf $patch_path
      continue
    }
    log_debug "keeping $patch_path"
  done
}
_hostname_hostname() {
  if [ -z "$_in_container" ]; then
    conf_os_installer_system_id=$(_hostname_get_system_id)
    conf_os_hostname=$conf_os_installer_system_name-$conf_os_installer_system_id
  else
    conf_os_hostname=$conf_os_installer_system_name
  fi
  printf '%s\n' $conf_os_hostname >/etc/hostname
  $GNU_SED -i "s/^127.0.0.1 localhost$/127.0.0.1 localhost $conf_os_hostname/" /etc/hosts
  $GNU_SED -i "s/^::1 localhost$/::1 localhost $conf_os_hostname/" /etc/hosts
}
_hostname_get_system_id() {
  dmidecode 2>/dev/null | grep 'Base Board Information' -A10 |
    grep 'Serial Number' | cut -f2 -d':' |
    sed -e 's/^ //' -e 's/ //g' -e 's/\//./g' -e 's/\.//g'
}
app_path=app
patch_app() {
  _module_find_filtered_callback app-install
}
patch_chmod() {
  _module_find_callback _chmod_do
}
_chmod_do() {
  local required path mode options
  . $1
  [ -z "$required" ] && [ ! -e "$path" ] && {
    log_detail "$path - not found, skipping"
    return
  }
  chmod $options $mode $path
}
patch_chown() {
  _module_find_callback _chown_do
}
_chown_do() {
  local owner group path options required
  . $1
  [ -z "$required" ] && [ ! -e "$path" ] && {
    log_detail "skipping chown for $path (not found)"
    return
  }
  chown $options $owner:$group $path
}
crontab_type=d
patch_crontab() {
  local crontabs_temp_path=$(_mktemp_options=d _mktemp_mktemp)
  _module_find_callback _crontab_do
  _crontab_users
}
_crontab_do() {
  local _crontabs_directory=$1
  local crontab_user=$(basename $_crontabs_directory)
  local crontab_user_file=$crontabs_temp_path/$crontab_user
  local crontab_path
  for crontab_path in $(find $_crontabs_directory -type f | sort -V); do
    printf '# %s\n' "$crontab_path" >>$crontab_user_file
    cat $crontab_path >>$crontab_user_file
  done
  chown $crontab_user:wheel $crontab_user_file
  unset _crontabs_directory crontab_user crontab_user_file crontab_path
}
_crontab_users() {
  local crontab_user_file crontab_user
  for crontab_user_file in $(find $crontabs_temp_path -type f | sort -u); do
    crontab_user=$(basename $crontab_user_file)
    log_info "updating $crontab_user crontab"
    _crontab_append $crontab_user $crontab_user_file
    rm -f $crontab_user_file
  done
}
patch_cups_printer() {
  _module_find_callback _cups_printer_add
}
_cups_printer_add() {
  _cups_printer_exists $1 && return
  log_info "adding $1"
  cat $1 >>$conf_os_installer_cups_conf_dir/printers.conf
}
_cups_printer_exists() {
  [ ! -e $conf_os_installer_cups_conf_dir/printers.conf ] && return 1
  local printer_uuid=$(grep ^UUID $1 | sed -e 's/UUID urn:uuid://')
  [ $(grep -c $printer_uuid $conf_os_installer_cups_conf_dir/printers.conf) -eq 0 ] && return 1
  log_warn "printer ($printer_uuid) already exists"
  return 0
}
patch_download() {
  mkdir -p /tmp/downloads
  _module_find_callback _do_download
}
_do_download() {
  . $1
  _download_fetch $uri
  local _output=/tmp/downloads/$(basename $download_file)
  cp $download_file $_output
  if [ -n "$signature" ]; then
    sha256 -c $signature $_output 2>/dev/null
    if [ $? -eq 0 ]; then
      printf '\tOK\n'
    else
      printf '\tFAIL\n'
    fi
  fi
  _extract_extract $_output
}
file_type=d
file_path='file'
patch_file() {
  for d in $(_module_find ! -execdir test -f .usr_local_etc \; -exec printf '%s\n' {} + | $GNU_GREP -Po '^.*\.patch/file' | sort -u); do
    rsync -lmrt $d/ /
  done
  for d in $(_module_find -execdir test -f .usr_local_etc \; -exec printf '%s\n' {} + | $GNU_GREP -Po '^.*\.patch/file' | sort -u); do
    rsync -lmrt $d/ /usr/local
  done
}
patch_fstab() {
  _module_find_callback _fstab_add
}
_fstab_add() {
  local _fstab=$1
  local patch_name=$(_module_get_patch_name $_fstab)
  printf '# %s\n' "$patch_name" >>/etc/fstab
  cat $_fstab >>/etc/fstab
  printf '\n' >>/etc/fstab
  unset _fstab patch_name
}
go_path=go
patch_go() {
  _module_find_filtered_callback _go_install_do
}
patch_group() {
  _module_find_callback _group_add
}
_group_add() {
  . $1
  log_detail "add group: $1 $groupName $gid"
  pw groupadd -n $groupName -g $gid
  unset groupName gid
}
patch_link() {
  _module_find_callback _link_do
}
_link_do() {
  . $1
  for _target in $targets; do
    log_detail "ln -sf $path -> $_target"
    local parent=$(dirname $_target)
    if [ ! -e $path ]; then
      log_warn "$path does NOT exist"
      continue
    elif [ ! -e $parent ]; then
      mkdir -p $parent
    fi
    ln -sf $path $_target
  done
  unset _target path targets
}
npm_path=npm
patch_npm() {
  _module_find_filtered_callback _NPM_INSTALL
}
package_path=package
patch_package() {
  _module_find_filtered_callback _package_install_new_only
}
package_uninstall_path=package_uninstall
patch_package_uninstall() {
  _module_find_filtered_callback _package_uninstall_do
}
patch_post_run() {
  _module_find_callback _post_run_do
  _post_run_restore_ssh
}
_post_run_do() {
  cd $conf_os_installer_system_workspace
  . $1
}
_post_run_restore_ssh() {
  log_detail "restoring SSH configuration (if applicable)"
  [ -e /root/.ssh.restore ] && _post_run_restore_ssh_do /root
  [ ! -e /home ] && return
  for s in $(find /home/ -maxdepth 2 -mindepth 2 -type d -name '.ssh.restore'); do
    _post_run_restore_ssh_do $(dirname $s)
  done
}
_post_run_restore_ssh_do() {
  log_warn "removing setup .ssh with .ssh.restore [$1]"
  rm -rf $1/.ssh
  mv $1/.ssh.restore $1/.ssh
}
pypi_path=pypi
patch_pypi() {
  _module_find_filtered_callback _pypi_install_do
}
patch_run() {
  _module_find_callback _run_do
}
_run_do() {
  cd $conf_os_installer_system_workspace
  . $1
}
rust_path=rust
patch_rust() {
  _module_find_filtered_callback _rust_install_do
}
patch_sysctl() {
  _module_find -exec $APP_PATH/bin/key_value /etc/sysctl.conf {} \;
  [ -n "$_in_container" ] && return
  _append_jail_sysctl
}
_append_jail_sysctl() {
  log_detail "appending jail sysctl"
  local container_mountpoint
  for container_mountpoint in $(_container_mount_points); do
    local sysctl_container_conf=$container_mountpoint/etc/sysctl.conf
    if [ -e $sysctl_container_conf ]; then
      log_detail "appending container sysctl: $container_mountpoint"
      printf '\n\n# %s container sysctl configuration\n' $(basename $container_mountpoint) >>/etc/sysctl.conf
      cat $sysctl_container_conf >>/etc/sysctl.conf
    else
      log_warn "container sysctl not found: $sysctl_container_conf"
    fi
  done
}
patch_user() {
  user_bootstrap || {
    log_warn "exit_with_error bootstrapping user module"
    return 1
  }
  _module_find_callback _user_add
}
_user_add() {
  backup_ssh=1
  _users_add $1
  unset backup_ssh
}
patch_zfs() {
  _module_find_callback _zfs_restore_do
  [ -z "$_in_container" ] && _zfs_handle_containers
  return 0
}
_zfs_restore_do() {
  local _zfs_volume_configuration=$1
  shift
  if [ -n "$_in_container" ]; then
    log_warn "processing jail ZFS configuration: $_zfs_volume_configuration"
    printf '_ZFS_JAILED=1\n' >>$_zfs_volume_configuration
    printf '_ZFS_JAIL=%s\n' $os_installer_jail_name >>$_zfs_volume_configuration
    printf '_ZFS_VOLUME_PREFIX=jails/%s\n' $os_installer_jail_name >>$_zfs_volume_configuration
    unset _zfs_volume_configuration
    return
  fi
  _zfs_restore
  unset _zfs_volume_configuration _ZFS_DEV_NAME _ZFS_SOURCE_HOST _ZFS_VOLUME_NAME _ZFS_VOLUME_ABORT_CREATE _ZFS_ZAP_SNAP _ZFS_ZAP_TTL _ZFS_ZAP_BACKUP _ZFS_MOUNT_POINT _zfs_volume _ZFS_JAILED _ZFS_JAIL
}
_zfs_handle_containers() {
  log_detail "processing container ZFS configurations"
  local container_mountpoint
  for container_mountpoint in $(_container_mount_points); do
    local container_name=$(basename $container_mountpoint)
    local zfs_container_path=$container_mountpoint/tmp/os
    if [ -e $zfs_container_path ]; then
      log_detail "processing container ZFS configuration: $container_name"
      local container_zfs_config
      for container_zfs_config in $(find $zfs_container_path -type f -path '*/zfs/*' 2>/dev/null); do
        _zfs_restore_do $container_zfs_config
      done
    fi
  done
}
_zfs_restore() {
  log_info "zfs_restore: $_zfs_volume_configuration"
  mkdir -p $HOME/.ssh/socket
  chmod 700 $HOME/.ssh/socket
  . $_zfs_volume_configuration
  [ -z "$_ZFS_DEV_NAME" ] && {
    log_warn "zfs_dev_name is empty"
    return 1
  }
  [ -z "$_ZFS_SOURCE_HOST" ] && {
    log_warn "zfs_source_host is empty"
    return 1
  }
  [ -z "$_ZFS_VOLUME_NAME" ] && {
    log_warn "zfs_volume_name is empty"
    return 1
  }
  if [ -n "$_ZFS_VOLUME_PREFIX" ]; then
    local _zfs_volume=${_ZFS_DEV_NAME}/${_ZFS_VOLUME_PREFIX}/$_ZFS_VOLUME_NAME
  else
    local _zfs_volume=${_ZFS_DEV_NAME}/$_ZFS_VOLUME_NAME
  fi
  local _zfs_source_snapshot=$(ssh $_ZFS_SOURCE_HOST zfs list -H -t snapshot | grep $_ZFS_VOLUME_NAME@ | grep -v backups | tail -1 | awk {'print$1'})
  [ -z "$_zfs_source_snapshot" ] && {
    log_warn "no snapshots available, unable to setup clone: $_zfs_volume"
    return 1
  }
  _zfs_has_sufficient_space || return 1
  local zfs_options
  zfs get -H encryption $_ZFS_DEV_NAME | awk {'print$4'} | grep -cqm1 '^off$' || {
    zfs_options=" -x encryption "
  }
  log_info "zfs create $_zfs_volume"
  ssh $_ZFS_SOURCE_HOST zfs send -v $_zfs_source_snapshot | zfs receive $zfs_options $_zfs_volume
  zfs set readonly=on $_zfs_volume
  [ -n "$_ZFS_MOUNT_POINT" ] && zfs set mountpoint=$_ZFS_MOUNT_POINT $_zfs_volume
  [ -n "$_ZFS_JAILED" ] && zfs set jailed=on $_zfs_volume
  zfs allow -g wheel bookmark,diff,hold,send,snapshot $_zfs_volume
  if [ -n "$_ZFS_SNAPSHOT_USER" ]; then
    mkdir -p $conf_os_installer_system_workspace/patches/any/zfs-snapshot-user-AUTO.patch/run/
    printf 'zfs allow -u %s bookmark,diff,hold,send,snapshot %s || log_warn "failed: zfs allow -u %s bookmark,diff,hold,send,snapshot %s"\n\n' $_ZFS_SNAPSHOT_USER $_zfs_volume $_ZFS_SNAPSHOT_USER $_zfs_volume \
      >>$conf_os_installer_system_workspace/patches/any/zfs-snapshot-user-AUTO.patch/run/allow-zfs-snapshot-user
    chmod +x $conf_os_installer_system_workspace/patches/any/zfs-snapshot-user-AUTO.patch/run/allow-zfs-snapshot-user
  fi
  _zfs_zap
  _zfs_rclone
  log_info "zfs create $_zfs_volume - done"
}
_zfs_has_sufficient_space() {
  local _zfs_snapshot_space=$(ssh $_ZFS_SOURCE_HOST zfs list -t snapshot $_zfs_source_snapshot | awk '{print$4}' | grep "G$" | sed -e "s/G$//")
  local _zfs_snapshot_required_space=$(printf '2 * %s\n' "$_zfs_snapshot_space" | bc)
  local _zpool_free_space=$(zpool list -H $_ZFS_DEV_NAME | awk '{print$4}' | grep "G$" | sed -e "s/G$//")
  if [ $(printf '%s < %s\n' "$_zfs_snapshot_required_space" "$_zpool_free_space" | bc) -eq 0 ]; then
    log_warn "insufficient free space: $_ZFS_VOLUME_NAME - $_zfs_snapshot_space $_zfs_snapshot_required_space $_zpool_free_space"
    return 1
  fi
  log_info "setting up $_ZFS_VOLUME_NAME - $_zfs_snapshot_space $_zfs_snapshot_required_space $_zpool_free_space"
}
_patches_patches() {
  for module in $@; do
    _module_set_log || {
      log_warn "$module already run, skipping"
      continue
    }
    required_message="$conf_os_installer_system_workspace - Configuration directory does not exist" file_require "$conf_os_installer_system_workspace"
    _module_run_build
    log_remove_context
  done
}
_module_set_log() {
  [ -z "$_index" ] && _index=0
  local module_logfile="/var/log/walterjwhite/${_index}.build.${module}"
  _index=$((_index + 1))
  [ -e $module_logfile ] && {
    return 1
  }
  _log_set_logfile $module_logfile
  log_add_context $module
}
_module_run_build() {
  cd $conf_os_installer_system_workspace
  eval "module_exec=\${${module}_exec}"
  eval "module_type=\${${module}_type}"
  eval "module_path=\${${module}_path}"
  eval "module_debug=\${${module}_debug}"
  [ -z "$module_type" ] && module_type=f
  [ -z "$module_path" ] && module_path="$module/*"
  [ -n "$module_debug" ] && set -x
  if [ $(_module_find -print -quit | wc -l) -eq 0 ]; then
    [ -n "$module_debug" ] && set +x
    log_info "no patches found - $module_type $module_path"
    unset module_exec module_type module_path module_debug
    return
  fi
  log_detail "start"
  patch_$module || {
    module_status=$?
    log_warn "module debug: $module_exec | $module_type | $module_path"
  }
  [ -n "$module_debug" ] && set +x
  _module_log_status $module $module_status
  unset module_exec module_type module_path module_debug
}
_platform_suffix() {
  if [ -n "$APP_PLATFORM_SUB_PLATFORM" ]; then
    printf '_%s_%s' "$APP_PLATFORM_PLATFORM" "$APP_PLATFORM_SUB_PLATFORM"
  else
    printf '_%s' "$APP_PLATFORM_PLATFORM"
  fi
}
_module_find() {
  local patch_path=physical
  [ -n "$_in_container" ] && patch_path=container
  local suffix
  suffix=$(_platform_suffix)
  find . -type "$module_type" ! -path '*/.archived/*' \
    -and \( -path '*/patches/any/*' -or -path "*/patches/$patch_path/*" \) \
    -and \( \
    -path "*/*.patch/${module_path}" \
    -or -path "*/*.patch${suffix}/${module_path}" \
    -or -path "*/*.patch/${module_path}${suffix}" \
    \) "$@" 2>/dev/null
}
_module_find_callback() {
  local element
  for element in $(_module_find); do
    log_add_context "$element"
    $1 "$element"
    log_remove_context
  done
}
_module_find_filtered() {
  _module_find -exec $GNU_GREP -Pvh '(^#|^$)' {} + | sort -V | tr '\n' ' ' | sed -e 's/ $/\n/'
}
_module_find_filtered_callback() {
  local element
  for element in $(_module_find_filtered); do
    log_add_context "$element"
    log_detail "start"
    $1 "$element" && log_detail "end - success" || {
      log_warn "end - error: $?"
    }
    log_remove_context
  done
}
_module_log_status() {
  if [ -n "$2" ]; then
    log_warn "end - exit_with_error ($2)"
  else
    log_detail "end - success"
  fi
}
_module_get_patch_name() {
  _module_get_patch_path "$1" |
    sed -e "s/^\.\///" -e "s/\.patch$//" -e "s/^patches\///"
}
_module_get_patch_path() {
  printf '%s' "$1" | $GNU_GREP -Po '^.*.\.patch'
}
_start_ssh() {
  _net_is_port_in_use 22
  if [ $? -eq 0 ]; then
    log_warn "unable to start SSHd as it is already running"
  else
    _start_service sshd
    local _sshd_started=1
  fi
  log_warn "ip: $(_net_ips)"
}
_stop_ssh() {
  [ -z "$_sshd_started" ] && return 1
  _stop_service sshd
}
_container_mount_points() {
  [ -e /var/lib/incus ] && {
    local container
    for container in $(find /var/lib/incus/storage-pools/default/containers -maxdepth 1 -mindepth 1 -type d); do
      printf '%s/rootfs\n' "$container"
    done
  }
  [ -d /var/lib/machines ] && {
    local container
    for container in $(find /var/lib/machines -maxdepth 1 -mindepth 1 -type d); do
      printf '%s\n' "$container"
    done
  }
}
_incus_setup_profile() {
  incus profile show default >/dev/null 2>&1 || exec_wrap incus admin init --auto
  incus profile show default | grep network | grep -cqm1 incusbr0 || {
    log_info "creating default networking conf"
    incus profile device add default eth0 nic network=incusbr0 name=eth0
  }
  incus profile show default | grep -A3 root | grep -A2 -B1 'path: /' | grep -A2 -B1 'pool: default' | grep -qm1 'type: disk' || {
    log_warn "adding disk to default profile"
    local zfs_root_dev_name=$(zfs get -H name / | awk {'print$1'} | cut -f1 -d/ | head -1)
    incus storage create default zfs source=$zfs_root_dev_name/incus
    exec_wrap incus profile device add default root disk pool=default path=/
    return
  }
  log_warn "default profile already contains disk device"
}
_incus_provision_container() {
  cd /tmp
  . $_INCUS_CONFIGURATION_FILE
  _incus_configuration_file_path=$(dirname $_INCUS_CONFIGURATION_FILE)
  _container_name=$os_installer_container_branch
  _container_path=/var/lib/incus/storage-pools/default/containers/$_container_name/rootfs
  _container_type=incus
  export _container_type=$_container_type
  export _container_name=$_container_name
  log_add_context "incus-$_container_name"
  conf_os_installer_system_name=$_container_name
  incus config show $_container_name >/dev/null 2>&1
  if [ $? -gt 0 ]; then
    log_detail "creating new instance [$_container_name]"
    exec_wrap incus launch images:$os_installer_container_image $_container_name
  else
    log_warn "using existing instance [$_container_name]"
    incus info $_container_name | grep Status | cut -f2 -d: | grep -cqm1 RUNNING || {
      log_detail "starting container"
      exec_wrap incus start $_container_name
    }
  fi
  incus config set $_container_name boot.host_shutdown_timeout=30
  o_os_installer_mountpoint=$conf_os_installer_mountpoint
  conf_os_installer_mountpoint=$_container_path
  mkdir -p $_container_path/tmp
  target=$_container_path _ssh_use_host_ssh_conf
  $GNU_SED -i 's/^hosts:.*/hosts: mymachines files myhostname dns/' $_container_path/etc/nsswitch.conf
  exec_wrap _prepare_chroot
  _init_chroot_ssh
  _init_chroot_app_conf
  local o_workspace=$conf_os_installer_system_workspace
  export conf_os_installer_system_workspace=/os
  exec_wrap _setup_git
  exec_wrap _write_system
  _incus_mount_kernel_src
  incus exec $_container_name -- systemctl restart systemd-resolved
  exec_call _incus_instance_prepare
  incus exec \
    --env _in_container=1 \
    --env conf_os_installer_system_name=$_container_name \
    --env logging_context=$logging_context \
    --env container=lxc $_container_name \
    --env add_log_context=incus-$_container_name \
    --env conf_os_installer_system_workspace=/os \
    --env optn_git_mirror=$optn_git_mirror \
    $APP_PLATFORM_PATH/$APPLICATION_NAME/bin/chroot
  exec_call _incus_instance_cleanup_running
  conf_os_installer_system_workspace=$o_workspace
  _incus_post_setup
  incus stop $_container_name
  exec_call _incus_instance_cleanup_stopped
  log_detail "creating ZFS snapshot"
  zap snap $os_installer_zap_snapshot_retention_duration default/containers/$_container_name
  conf_os_installer_mountpoint=$o_os_installer_mountpoint
  log_remove_context
  unset _container_type _container_name
}
_incus_mount_kernel_src() {
  [ -e /usr/src ] && {
    mkdir -p $_container_path/usr/src
    mount --bind /usr/src $_container_path/usr/src
    exit_defer umount $_container_path/usr/src
  }
}
_incus_start() {
  systemctl enable incus && systemctl enable incus-user
  systemctl start incus && exit_defer systemctl stop incus
  systemctl start incus-user && exit_defer systemctl stop incus
}
_incus_post_setup() {
  if [ -e $_incus_configuration_file_path/post-setup ]; then
    log_info "running post-setup scripts for $_container_name"
    local post_setup_script
    for post_setup_script in $(find $_incus_configuration_file_path/post-setup -type f | sort); do
      log_info "running $post_setup_script"
      . $post_setup_script
    done
  fi
}
incus_path=incus
patch_incus() {
  [ -n "$_in_container" ] && {
    log_warn "in container, aborting"
    return
  }
  _patch_incus_pre
  _incus_setup_profile
  for _INCUS_CONFIGURATION_FILE in $(find /tmp/os -type f -path '*.patch/incus' | sort); do
    log_info "provisioning incus container: $_INCUS_CONFIGURATION_FILE"
    _incus_provision_container "$_INCUS_CONFIGURATION_FILE"
  done
  log_detail "after patch_incus"
}
_patch_incus_pre() {
  patch_incus_prepare_${distribution_function_name}
  grep -qm1 'root:1000000' /etc/subuid || {
    log_detail "configuring users and groups for incus"
    printf 'root:1000000:1000000000\n' | tee -a /etc/subuid /etc/subgid >/dev/null
  }
  _incus_start
  command -v nft >/dev/null 2>&1 || return
  log_warn 'flushing nftables rules and restarting nftables'
  nft flush ruleset
  systemctl restart nftables
}
patch_incus_prepare_arch() {
  _package_install_new_only incus
}
patch_incus_prepare_gentoo() {
  _package_install_new_only app-containers/incus
}
patch_lxd() {
  [ -n "$_in_container" ] && return
  log_warn "not implemented - lxd"
}
use_path=use
patch_use() {
  local use=$(_module_find_filtered | sort -u | tr '\n' ' ')
  [ -z "$use" ] && return
  printf '# portage use - patches\nUSE="$USE %s"\n' "$use" >>/etc/portage/make.conf
}
patch_service() {
  _module_find_callback _service_do
}
_service_do() {
  local service_line
  $GNU_GREP -Pvh '^($|#)' "$1" | while read service_line; do
    [ -z "$service_line" ] && {
      log_warn "service_line was empty"
      continue
    }
    systemctl enable $service_line
  done
}
_net_is_port_in_use() {
  ss -tuln | grep -Pcqm1 ':$1[\s]'
}
_net_ips() {
  ip -o -f inet addr show | awk '$3 !~ /lo/ && $4 !~ /127.0.0.1/ {print $4}' | tr '\n' ' '
}
init_bliss() {
  _package_install_new_only bliss-initramfs
}
init_dracut() {
  mkdir -p /etc/dracut.conf.d
  printf 'sys-kernel/installkernel dracut\n' >>/etc/portage/package.use/installkernel
  local dracut_modules
  [ -n "$_os_installer_disk_dev_encrypted" ] && {
    dracut_modules="$dracut_modules crypt "
  }
  [ -n "$_os_installer_zfs_pool_name" ] && {
    [ "$os_installer_boot_fs" = "zpool" ] && {
      dracut_modules="$dracut_modules zfs"
    }
  }
  [ -z "$os_installer_fsck" ] && printf 'nofsck="yes"\n' >>/etc/dracut.conf.d/no-fsck.conf
  printf 'add_dracutmodules+=" %s"\n' "$dracut_modules " >>/etc/dracut.conf.d/modules.conf
}
init_ugrd() {
  mkdir -p /etc/portage/package.use /etc/portage/package.accept_keywords
  printf 'sys-kernel/installkernel ugrd\n' >>/etc/portage/package.use/installkernel
  [ -n "$_os_installer_zfs_pool_name" ] && {
    printf 'dev-python/zenlib **\n' >>/etc/portage/package.accept_keywords/ugrd
    printf 'dev-python/pycpio **\n' >>/etc/portage/package.accept_keywords/ugrd
    printf 'sys-kernel/installkernel **\n' >>/etc/portage/package.accept_keywords/ugrd
    printf 'sys-kernel/ugrd **\n' >>/etc/portage/package.accept_keywords/ugrd
  }
}
init_walterjwhite() {
  $APP_PATH/bin/gentoo-build-init $_os_installer_zfs_pool_name
}
kernel_main_arch() {
  :
}
kernel_zfs_support_arch() {
  :
}
kernel_main_gentoo() {
  _kernel_conf
  _kernel_luks_support
  _package_install_new_only sys-kernel/$os_installer_kernel
  _kernel_zfs_support_gentoo
  _kernel_initramfs
}
_kernel_conf() {
  case $os_installer_init in
  bliss | dracut | ugrd)
    printf 'USE="$USE %s"\n' "$os_installer_init" >>/etc/portage/make.conf
    ;;
  esac
  case $os_installer_kernel in
  *-kernel | *-kernel-bin)
    _os_installer_dist_kernel=1
    printf 'USE="$USE dist-kernel"\n' >>/etc/portage/make.conf
    ;;
  *)
    printf 'USE="$USE symlink"\n' >>/etc/portage/make.conf
    ;;
  esac
}
_kernel_zfs_support_gentoo() {
  [ "$os_installer_boot_fs" != "zpool" ] && {
    log_warn "boot -> $os_installer_boot_fs, skipping ZFS"
    return 1
  }
  [ -z "$_os_installer_zfs_pool_name" ] && {
    log_warn "pool name not set: $_os_installer_zfs_pool_name, skipping ZFS"
    return 2
  }
  [ -n "$_os_installer_dist_kernel" ] && {
    [ -z "$_in_container" ] && {
      printf 'sys-fs/zfs dist-kernel-cap\n' >>/etc/portage/package.use/zfs
    }
  }
  _package_install_new_only sys-fs/zfs-kmod
  _package_install_new_only sys-fs/zfs
  _kernel_zfs_service_systemd
}
_kernel_zfs_service_systemd() {
  systemctl enable zfs.target
  systemctl enable zfs-import-cache
  systemctl enable zfs-mount
  systemctl enable zfs-import.target
  systemctl enable zfs-trim-monthly@${_os_installer_zfs_pool_name}.timer
  systemctl enable zfs-scrub-monthly@${_os_installer_zfs_pool_name}.timer
  systemctl enable zfs-trim-weekly@${_os_installer_zfs_pool_name}.timer
  systemctl enable zfs-scrub-weekly@${_os_installer_zfs_pool_name}.timer
}
_kernel_luks_support() {
  [ -n "$_os_installer_disk_dev_encrypted" ] && _package_install_new_only sys-fs/cryptsetup
}
_kernel_initramfs() {
  init_$os_installer_init
  case $os_installer_init in
  bliss | dracut | ugrd)
    emerge --config sys-kernel/$os_installer_kernel
    ;;
  esac
}
system_locale_arch() {
  :
}
time_synchronization_arch() {
  local time_sync_packages
  case $os_installer_time_synchronization in
  chronyd)
    time_sync_packages=chrony
    ;;
  ntpd)
    time_sync_packages=ntp
    ;;
  timedatectl)
    [ -n "$os_installer_time_synchronization_enable_ntp" ] && timedatectl set-ntp true
    return
    ;;
  esac
  _package_install_new_only $time_sync_packages
}
system_firmware_arch() {
  _package_install_new_only linux-firmware
}
system_cpu_vendor_firmware_intel_arch() {
  _package_install_new_only intel-ucode
}
system_cpu_vendor_firmware_amd_arch() {
  _package_install_new_only amd-ucode
}
system_cron_arch() {
  local cron_packages
  case $conf_cron_provider in
  cronie | fcron)
    cron_packages=$conf_cron_provider
    ;;
  bcron | dcron)
    exit_with_error "$conf_cron_provider is not presently supported"
    ;;
  systemd)
    log_warn "using systemd cron mechanism"
    return 0
    ;;
  esac
}
system_syslog_arch() {
  :
}
system_indexing_arch() {
  case $os_installer_indexing in
  plocate)
    indexing_packages=plocate
    _updatedb_cmd=/usr/bin/updatedb
    ;;
  *)
    exit_with_error "unknown indexing provider: $os_installer_indexing"
    ;;
  esac
}
system_pre_arch() {
  :
}
system_post_arch() {
  :
}
system_locale_gentoo() {
  printf '%s\n' "$os_installer_system_locale_gen" | tr '|' '\n' >/etc/locale.gen
  locale-gen
  eselect locale set $os_installer_system_locale_eselect
  . /etc/profile
}
time_synchronization_gentoo() {
  local time_sync_packages
  case $os_installer_time_synchronization in
  chronyd)
    time_sync_packages=net-misc/chrony
    ;;
  ntpd)
    time_sync_packages=net-misc/ntp
    mkdir -p /etc/portage/package.use
    printf 'net-misc/ntp openntpd\n' >>/etc/portage/package.use/ntp
    ;;
  timedatectl)
    [ -n "$os_installer_time_synchronization_enable_ntp" ] && timedatectl set-ntp true
    return
    ;;
  esac
  _package_install_new_only $time_sync_packages
}
system_firmware_gentoo() {
  mkdir -p /etc/portage/package.license
  printf 'sys-kernel/linux-firmware linux-fw-redistributable\n' >>/etc/portage/package.license/firmware
  _package_install_new_only sys-kernel/linux-firmware
}
system_cpu_vendor_firmware_intel_gentoo() {
  printf 'sys-firmware/intel-microcode intel-ucode\n' >>/etc/portage/package.license/firmware
  _package_install_new_only sys-firmware/intel-microcode
}
system_cpu_vendor_firmware_amd_gentoo() {
  :
}
system_cron_gentoo() {
  local cron_packages
  case $conf_cron_provider in
  cronie | bcron | dcron | fcron)
    cron_packages=sys-process/$conf_cron_provider
    ;;
  systemd)
    log_warn "using systemd cron mechanism"
    return 0
    ;;
  esac
  _package_install_new_only $cron_packages
  systemctl enable $conf_cron_provider
}
system_syslog_gentoo() {
  local service_name="$os_installer_syslog"
  case $os_installer_syslog in
  sysklogd)
    [ -n "$os_installer_syslog_use" ] && printf 'app-admin/sysklogd %s\n' "$os_installer_syslog_use" >>/etc/portage/package.use/sysklogd
    syslog_packages=app-admin/sysklogd
    syslog_service_name=syslogd.service
    ;;
  *)
    exit_with_error "unknown syslog provider: $os_installer_syslog"
    ;;
  esac
}
system_indexing_gentoo() {
  case $os_installer_indexing in
  plocate)
    indexing_packages=sys-apps/plocate
    _updatedb_cmd=/usr/bin/updatedb
    ;;
  *)
    exit_with_error "unknown indexing provider: $os_installer_indexing"
    ;;
  esac
}
system_pre_gentoo() {
  local original_log_file=$log_logfile
  module=newuse _module_set_log
  _exec_attempts=3 exec_wrap package_update
  log_detail "packages updated"
  _log_set_logfile $original_log_file
  unset original_log_file
}
system_post_gentoo() {
  _patches_patches use
  module=newuse _module_set_log
  _exec_attempts=3 exec_wrap package_update
}
_system_main() {
  system_locale_${distribution_function_name}
  [ -z "$_in_container" ] && time_synchronization_${distribution_function_name}
  system_pre_${distribution_function_name}
  if [ -z "$_in_container" ]; then
    system_firmware_${distribution_function_name}
    _system_cpu_vendor_firmware
    kernel_main_${distribution_function_name}
  else
    kernel_zfs_support_${distribution_function_name}
  fi
  _system_cron
  _system_syslog
  _system_indexing
  system_post_${distribution_function_name}
}
_system_patches() {
  _patches_patches lxd incus
}
_system_cpu_vendor_firmware() {
  cpu_vendor=$(lscpu | grep '^Vendor ID:' | awk {'print$3'})
  case $cpu_vendor in
  *Intel*)
    cpu_vendor=Intel
    system_cpu_vendor_firmware_intel_${distribution_function_name}
    ;;
  *AMD*)
    cpu_vendor=AMD
    system_cpu_vendor_firmware_amd_${distribution_function_name}
    ;;
  *)
    exit_with_error "unsupported CPU $cpu_vendor"
    ;;
  esac
}
_system_cron() {
  system_cron_${distribution_function_name}
  [ -z "$cron_packages" ] && return
  _package_install_new_only $cron_packages
  systemctl enable $conf_cron_provider
}
_system_syslog() {
  system_syslog_${distribution_function_name}
  [ -z "$syslog_packages" ] && return
  _package_install_new_only $syslog_packages
  systemctl enable $syslog_service_name
}
_system_indexing() {
  system_indexing_${distribution_function_name}
  _package_install_new_only $indexing_packages
}
_run_run() {
  log_info "$*"
  local run_file=${_os_installer_exec_dir}/$1
  [ -e $run_file ] && {
    log_warn "$* already run, skipping"
    return
  }
  mkdir -p ${_os_installer_exec_dir}
  touch $run_file
  "$@"
}
_setup_git() {
  _os_installer_system_workspace_path=${conf_os_installer_mountpoint}$conf_os_installer_system_workspace
  rm -rf $_os_installer_system_workspace_path
  _setup_git_clone $conf_os_installer_system_name $_os_installer_system_workspace_path
  cd $_os_installer_system_workspace_path
}
_setup_git_clone() {
  mkdir -p $2
  git archive --remote $conf_os_installer_system_git $1 | tar xp -C $2 || {
    exit_with_error "error setting up git $conf_os_installer_system_git [$*]"
  }
  cd $2
  [ -e .import ] || {
    log_detail "no imports detected - $2"
    return
  }
  local git_import_contents=$(head -1 .import)
  log_add_context $git_import_contents
  log_detail "setting up import"
  _setup_git_clone $git_import_contents $_os_installer_system_workspace_path/imports/$git_import_contents
  log_remove_context
}
_start_service() {
  systemctl start $1
}
_stop_service() {
  systemctl stop $1
}
_crontab_get() {
  validation_require "$1" "Crontab User"
  validation_require "$2" "Crontab Filename to write to"
  crontab_${conf_cron_provider}_get "$@"
}
_crontab_append() {
  validation_require "$1" "Crontab User"
  file_require "$2" "Crontab File"
  _file_has_contents $2 || return 1
  local current_crontab=$(_mktemp_mktemp)
  [ "$1" = "root" ] && chown $1: $current_crontab
  _crontab_get $1 $current_crontab
  _crontab_run "$1" sh -c 'cat "$1" >> "$2"' _ "$2" "$current_crontab"
  crontab_${conf_cron_provider}_write "$1" "$current_crontab"
  _crontab_run "$1" rm -f "$current_crontab"
}
crontab_default_clear() {
  _crontab_run "$1" crontab -r 2>/dev/null
}
crontab_default_get() {
  _crontab_run "$1" sh -c 'crontab -l > "$1" 2>/dev/null || true' _ "$2"
}
crontab_default_write() {
  _crontab_default_header "$1" "$2"
  _crontab_run "$1" crontab "$2" || {
    log_warn "error writing crontab"
    _crontab_run "$1" cat "$2"
  }
}
_crontab_default_header() {
  [ ! -e "$2" ] && {
    log_warn "crontab file $2 does not exist"
    return 1
  }
  [ -z "$optn_install_crontab_header" ] && return 0
  local _header="$optn_install_crontab_header"
  _crontab_run "$1" sh -c 'printf "%s\n\n" "$1" > "$2.new"' _ "$_header" "$2"
  _crontab_run "$1" sh -c 'cat "$1" >> "$1.new" && mv "$1.new" "$1"' _ "$2"
}
_crontab_run() {
  local _user="$1"
  shift
  if [ "$_user" = "root" ]; then
    sudo_user=root sudo_run "$@"
  else
    "$@"
  fi
}
crontab_dcron_clear() {
  case $1 in
  root)
    sudo_user=$1 sudo_run crontab /etc/crontab
    ;;
  *)
    sudo_user=$1 sudo_run crontab -d
    ;;
  esac
}
crontab_dcron_get() {
  sudo_user=$1 sudo_run crontab -l | sudo_user=$1 sudo_run tee $2 >/dev/null 2>&1
}
crontab_dcron_write() {
  sudo_user=$1 sudo_run crontab $2
}
_extract_extract() {
  if [ $# -lt 2 ]; then
    log_warn "expecting 2 arguments, source file, and target to extract to"
    return 1
  fi
  log_info "extracting $1"
  [ -n "$clean" ] && {
    rm -rf $2
    mkdir -p $2
  }
  case $1 in
  *.tar.gz | *.tgz | *.tar.bz2 | *.tbz2 | *.tar.xz)
    tar xf $1 -C $2
    ;;
  *.zip)
    unzip -q $1 -d $2
    ;;
  *)
    log_warn "extension unsupported - $1"
    return 2
    ;;
  esac
}
go_bootstrap() {
  _go_set_proxy
  _go_bootstrap_is_go_available || {
    _package_install_new_only $GO_PACKAGE
    _go_bootstrap_is_go_available || go_disabled=1
  }
}
_go_set_proxy() {
  [ -z "$http_proxy" ] && return
  git config --global http.proxy $http_proxy
  git config --global https.proxy $https_proxy
  exit_defer _go_clear_proxy
}
_go_clear_proxy() {
  git config --global --unset http.proxy
  git config --global --unset https.proxy
}
_go_bootstrap_is_go_available() {
  command -v go >/dev/null 2>&1
}
_go_walterjwhite_conf() {
  [ -e ./.build/go ] && . ./.build/go
  local _app_name=$(basename $1 | sed -e 's/@.*//')
  local _build_date=$(date +"%Y/%m/%d-%H:%M:%S")
  local _version=$(git branch --no-color --show-current)
  local _scm_id=$(git rev-parse HEAD)
  local _go_version=$(go version | awk {'print$3'} | sed 's/-X:.*//')
  local _os_architecture=$(go version | awk {'print$4'})
  local _app_name_flag="github.com/walterjwhite/go-code/lib/application.ApplicationName=$_app_name"
  local _app_version_flag="github.com/walterjwhite/go-code/lib/application.ApplicationVersion=$_version"
  local _scm_version_id_flag="github.com/walterjwhite/go-code/lib/application.SCMId=$_scm_id"
  local _build_date_flag="github.com/walterjwhite/go-code/lib/application.BuildDate=$_build_date"
  local _go_version_flag="github.com/walterjwhite/go-code/lib/application.GoVersion=$_go_version"
  local _os_architecture_flag="github.com/walterjwhite/go-code/lib/application.OSArchitecture=$_os_architecture"
  go_build_options="-X $_app_name_flag -X $_app_version_flag -X $_scm_version_id_flag -X $_build_date_flag -X $_go_version_flag -X $_os_architecture_flag"
  [ -n "$output_build_filename" ] && {
    go_build_options="$go_build_options -o $output_build_filename"
    unset output_build_filename
  }
  log_debug "build flags:"
  log_debug "$_app_name_flag"
  log_debug "$_app_version_flag"
  log_debug "$_scm_version_id_flag"
  log_debug "$_build_date_flag"
  log_debug "$_go_version_flag"
  log_debug "$_os_architecture_flag"
}
_go_install_do() {
  _go_is_installed $1 && {
    log_detail "$1 is already installed"
    return 0
  }
  case $1 in
  *github.com/walterjwhite/*)
    _go_walterjwhite_conf "$1"
    ;;
  *)
    log_debug "using standard go properties"
    ;;
  esac
  (
    if [ -n "$go_build_options" ]; then
      env GOPATH="$conf_install_go_path" CGO_ENABLED=1 go install -a -race -ldflags "$go_build_options" "$1"
    else
      env GOPATH="$conf_install_go_path" CGO_ENABLED=1 go install -a -race "$1"
    fi
  ) || {
    log_warn "go install failed: env GOPATH='$conf_install_go_path' CGO_ENABLED=1 go install -a -race '$go_build_options' $1"
    log_warn "http_proxy: $http_proxy"
    log_warn "git  proxy: $(git config --global http.proxy)"
  }
}
_go_is_installed() {
  local cmd_name=$(basename $(printf '%s\n' "$1" | sed 's/@.*//; s/\/v[0-9]*$//'))
  [ -e "$conf_install_go_path/bin/$cmd_name" ]
}
npm_bootstrap() {
  _npm_bootstrap_is_npm_available || {
    _npm_bootstrap_pre
    _package_install_new_only $NPM_PACKAGE
    _npm_bootstrap_is_npm_available || npm_disabled=1
  }
  _npm_setup_proxy
  exec_call npm_bootstrap_platform
}
_npm_bootstrap_pre() {
  :
}
_npm_bootstrap_is_npm_available() {
  command -v npm >/dev/null 2>&1
}
_npm_prefix() {
  printf '%s' "$TARGET_APP_PLATFORM_BIN_PATH" | sed -e 's/\/bin$//'
}
_npm_is_installed() {
  npm list -g --prefix "$(_npm_prefix)" "$1" >/dev/null 2>&1
}
_npm_setup_proxy() {
  [ -z "$http_proxy" ] && return
  log_warn "configuring NPM to use an HTTP proxy: $http_proxy"
  npm config set proxy $http_proxy
  npm config set https-proxy $https_proxy
  exit_defer _npm_clear_proxy
}
_npm_clear_proxy() {
  log_warn "reverting NPM HTTP proxy: $http_proxy"
  npm config rm proxy
  npm config rm https-proxy
}
_package_install_new_only() {
  [ $# -eq 0 ] && return
  local package_install_packages=""
  local package
  for package in "$@"; do
    _package_is_installed $package || {
      if [ -n "$package_install_packages" ]; then
        package_install_packages="$package_install_packages $package"
      else
        package_install_packages="$package"
      fi
    }
  done
  if [ -n "$package_install_packages" ]; then
    _package_install_do $package_install_packages
  else
    log_warn "packages [$*] are already installed, skipping"
    return 0
  fi
}
pypi_bootstrap() {
  _pypi_bootstrap_is_pypi_available || {
    _package_install_new_only $PYPI_PACKAGE
    _pypi_bootstrap_is_pypi_available || pypi_disabled=1
  }
}
_pypi_bootstrap_is_pypi_available() {
  command -v pip >/dev/null 2>&1
}
_pypi_install_do() {
  if [ "${INSTALL_TARGET:-USER}" = "SYSTEM" ]; then
    sudo_run pip install -U --no-input "$1" >/dev/null
  else
    pip install -U --no-input --user "$1" >/dev/null
  fi
}
rust_bootstrap() {
  _rust_bootstrap_is_rust_available || {
    _package_install_new_only $RUST_PACKAGE
    _rust_bootstrap_is_rust_available || rust_disabled=1
  }
}
_rust_bootstrap_is_rust_available() {
  command -v cargo >/dev/null 2>&1
}
_rust_root_dir() {
  printf '%s' "$TARGET_APP_PLATFORM_BIN_PATH" | sed -e 's/\/bin$//'
}
_rust_install_do() {
  _rust_is_installed $1 && {
    log_detail "$1 is already installed"
    return 0
  }
  cargo install --root=$(_rust_root_dir) "$@"
}
rust_update() {
  cargo update "$@"
}
_rust_is_installed() {
  cargo install --root=$(_rust_root_dir) --list | grep -cqm1 "^$1 .*:$"
}
rust_is_latest() {
  :
}
aur_package_install() {
  aur_package_install_new_only $(_install_filter_file $1)
}
aur_package_install_new_only() {
  [ $# -eq 0 ] && return
  local package_install_packages=""
  local package
  for package in "$@"; do
    aur_package_is_installed $package || {
      if [ -n "$package_install_packages" ]; then
        package_install_packages="$package_install_packages $package"
      else
        package_install_packages="$package"
      fi
    }
  done
  if [ -n "$package_install_packages" ]; then
    aur_package_install_do $package_install_packages
  else
    log_warn "packages [$*] are already installed, skipping"
    return 0
  fi
}
aur_package_install_do() {
  flags="-Sqyu --noconfirm"
  _aur_cmd "$@"
}
aur_package_uninstall() {
  _install_uninstall_filter_file_callback $1 aur_package_uninstall_do
}
aur_package_uninstall_do() {
  flags="-Rq --noconfirm"
  _aur_cmd "$@"
}
aur_package_is_installed() {
  flags="-Q"
  _aur_cmd "$@"
}
aur_package_update() {
  flags="-Syuq --noconfirm"
  _aur_cmd "$@"
}
aur_package_bootstrap() {
  sudo_run getent passwd builduser >/dev/null 2>&1 && return
  sudo_run useradd -m builduser
  printf "builduser ALL=(ALL) NOPASSWD: ALL\n" | sudo_run tee /etc/sudoers.d/builduser
  sudo_run chmod 440 /etc/sudoers.d/builduser
  flags="-Sqyu --noconfirm"
  _pacman_cmd paru
}
_aur_cmd() {
  [ "$#" -eq 0 ] && return
  [ "$APP_PLATFORM_ROOT" = "/" ] && {
    su - builduser -c "paru $flags $@" 2>&1 >/dev/null
    return
  }
  [ "$_container_type" = "incus" ] && {
    log_warn "detected incus container, using incus exec"
    sudo_run incus exec $_container_name -- su - builduser -c "paru $flags $@" 2>&1 >/dev/null
    return
  }
  su - builduser -c "paru $flags --sysroot $APP_PLATFORM_ROOT $@" 2>&1 >/dev/null
}
package_emerge_requires_reboot() {
  :
}
package_emerge_install_do() {
  _emerge_portage_sync
  _package_emerge_cmd "$@"
}
package_emerge_uninstall_do() {
  _package_emerge_cmd $emerge_options --depclean "$@"
}
_package_emerge_cmd() {
  local log_target=/dev/null
  [ -n "$log_logfile" ] && log_target=$log_logfile
  [ "$APP_PLATFORM_ROOT" != "/" ] && {
    _emerge_portage_run_in_chroot "$@" >>$log_target 2>&1
    return
  }
  sudo_run emerge $EMERGE_FLAGS "$@" >>$log_target 2>&1
}
_emerge_portage_run_in_chroot() {
  _emerge_portage_setup_chroot_mounts
  sudo_run chroot $APP_PLATFORM_ROOT emerge $EMERGE_FLAGS "$@"
  _emerge_portage_setup_chroot_mounts_cleanup
}
package_emerge_is_installed() {
  local _package=$1
  shift
  [ -f $APP_PLATFORM_ROOT/var/lib/portage/world ] && {
    $GNU_GREP -Pqm1 "^${_package}$" $APP_PLATFORM_ROOT/var/lib/portage/world && {
      return 0
    }
  }
  local package_group=$(printf '%s' $_package | cut -f1 -d/)
  local package_name=$(printf '%s' $_package | cut -f2 -d/)
  if [ -e $APP_PLATFORM_ROOT/var/db/pkg/$package_group ]; then
    find $APP_PLATFORM_ROOT/var/db/pkg/$package_group -type f -name "$package_name-*.ebuild" | grep -Pqm1 '.' && {
      return 0
    }
  fi
}
package_emerge_bootstrap() {
  [ -n "$emerge_package_disabled" ] && return
  mount | grep ' overlay on / ' | grep -v '/var/lib/docker' | grep -cqm1 '.' && {
    log_warn 'disabling emerge as it appears we are running on an overlayfs'
    emerge_package_disabled=1
    return 1
  }
  _emerge_portage_setup_chroot_mounts_with_root
  _emerge_portage_use_git
  _emerge_portage_mirrors
  _emerge_portage_sync
  _emerge_portage_package_accept_keywords
}
package_emerge_update() {
  _emerge_portage_sync
  log_info "updating world packages"
  _package_emerge_cmd --newuse -uD world "$@"
  log_info "updated world packages"
  if [ -n "$optn_install_gentoo_depclean" ]; then
    log_info "running depclean"
    _package_emerge_cmd $emerge_options --depclean $@
    log_info "depclean completed"
  fi
}
emerge_package_bootstrap_is_package_available() {
  return 0
}
_emerge_portage_setup_chroot_mounts_with_root() {
  [ "$APP_PLATFORM_ROOT" = "/" ] && return
  sudo_run mkdir -p $APP_PLATFORM_ROOT/dev $APP_PLATFORM_ROOT/run $APP_PLATFORM_ROOT/sys $APP_PLATFORM_ROOT/proc $APP_PLATFORM_ROOT/var/db/repos
  _emerge_portage_mount_rbind dev
  _emerge_portage_mount_rbind run
  _emerge_portage_mount_rbind sys
  sudo_run mount --types proc /proc $APP_PLATFORM_ROOT/proc
  [ -e /var/db/repos ] && sudo_run mount --bind /var/db/repos $APP_PLATFORM_ROOT/var/db/repos
}
_emerge_portage_setup_chroot_mounts_cleanup() {
  [ "$APP_PLATFORM_ROOT" = "/" ] && return
  sudo_run umount -R $APP_PLATFORM_ROOT/dev $APP_PLATFORM_ROOT/run $APP_PLATFORM_ROOT/sys $APP_PLATFORM_ROOT/proc $APP_PLATFORM_ROOT/var/db/repos
}
_emerge_portage_mount_rbind() {
  local mount_point=$1
  sudo_run mount --rbind /$mount_point $APP_PLATFORM_ROOT/$mount_point
  sudo_run mount --make-rslave $APP_PLATFORM_ROOT/$mount_point
}
mask_bootstrap() {
  :
}
mask_install() {
  _utils_portage_install_file package.mask $1
}
mask_uninstall() {
  _utils_portage_uninstall_file package.mask $1
}
mask_is_installed() {
  _utils_portage_is_installed package.mask $1
}
mask_enabled() {
  return 0
}
mask_is_file() {
  return 0
}
package_accept_keywords_bootstrap() {
  :
}
package_accept_keywords_install() {
  _utils_portage_install_file package.accept_keywords $1
}
package_accept_keywords_uninstall() {
  _utils_portage_uninstall_file package.accept_keywords $1
}
package_accept_keywords_is_installed() {
  _utils_portage_is_installed package.accept_keywords $1
}
package_accept_keywords_enabled() {
  return 0
}
package_accept_keywords_is_file() {
  return 0
}
package_license_bootstrap() {
  :
}
package_license_install() {
  _utils_portage_install_file package.license $1
}
package_license_uninstall() {
  _utils_portage_uninstall_file package.license $1
}
package_license_is_installed() {
  _utils_portage_is_installed package.license $1
}
package_license_enabled() {
  return 0
}
package_license_is_file() {
  return 0
}
package_use_bootstrap() {
  :
}
package_use_install() {
  _utils_portage_install_file package.use $1
}
package_use_uninstall() {
  _utils_portage_uninstall_file package.use $1
}
package_use_is_installed() {
  _utils_portage_is_installed package.use $1
}
package_use_enabled() {
  return 0
}
package_use_is_file() {
  return 0
}
use_bootstrap() {
  :
}
use_install() {
  local _name_suffix=$(_utils_get_feature_name $1)
  printf '# app.%s%s\n' $target_application_name "$_name_suffix" >>/etc/portage/make.conf
  printf 'USE="$USE %s"\n' "$(cat $1)" >>/etc/portage/make.conf
  unset _name_suffix
}
use_uninstall() {
  local _name_suffix=$(_utils_get_feature_name $1)
  $GNU_SED -i "s/ app.$target_application_name${_name_suffix}/ /" /etc/portage/make.conf
  unset _name_suffix
}
use_is_installed() {
  local _name_suffix=$(_utils_get_feature_name $1)
  grep -qm1 " # app.$target_application_name${_name_suffix}" /etc/portage/make.conf
  unset _name_suffix
}
use_enabled() {
  return 0
}
use_is_file() {
  return 0
}
app_default_bootstrap() {
  :
}
app_default_install() {
  local _desktop=$1
  local _file_type=$2
  if [ -n "$USER" ]; then
    sudo_user="$USER" sudo_run xdg-mime default "$_desktop.desktop" "$_file_type"
    local _result=$?
    unset _desktop _file_type
    return $_result
  fi
  xdg-mime default "$_desktop.desktop" "$_file_type"
  local _result=$?
  unset _desktop _file_type
  return $_result
}
app_default_uninstall() {
  :
}
app_default_is_installed() {
  :
}
app_default_enabled() {
  return 0
}
_npm_bootstrap_pre() {
  case $APP_PLATFORM_SUB_PLATFORM in
  Gentoo)
    local _use_flag_file=/tmp/install-gentoo-npm.use
    printf '%s npm\n' $NPM_PACKAGE >$_use_flag_file
    package_use_install $_use_flag_file
    rm -f $_use_flag_file
    unset _use_flag_file
    ;;
  esac
}
user_bootstrap() {
  log_detail "bootstrapping user module"
  sudo_run mkdir -p /root/.ssh/socket
  sudo_run chmod -R 700 /root/.ssh/socket
  app-install configuration
  log_detail "bootstrapped user module"
}
user_install() {
  _users_add "$1"
}
user_uninstall() {
  . "$1"
  validation_require "$username" "username"
  sudo_run userdel $username
}
_users_add_argument() {
  local _option=$1
  local _value=$2
  [ -n "$_value" ] && user_options="$user_options $_option $_value"
}
_users_add() {
  . $1
  log_add_context $username
  if [ "$username" != "root" ]; then
    getent passwd $username >/dev/null 2>&1
    if [ $? -eq 0 ]; then
      log_info "user already exists"
      [ -n "$home" ] && {
        log_info "setting user home: $home"
        sudo_run usermod -m -d $home $username
      }
    else
      log_info "add user: $1: $username"
      user_options="-m"
      _users_add_argument "-g" "$gid"
      _users_add_argument "-G" "$grouplist"
      _users_add_argument "-s" "$shell"
      _users_add_argument "-u" "$uid"
      _users_add_argument "-p" "$password"
      sudo_run useradd $user_options $username
    fi
  else
    [ -n "$shell" ] && {
      log_info "setting shell to $shell"
      sudo_run chsh -s "$shell"
    }
    if [ -n "$password" ]; then
      log_info "setting password"
      sudo_run usermod -p "$_password" $username
    fi
  fi
  _users_configure
  unset user_options username gid grouplist shell uid password system
  log_remove_context
}
_users_configure() {
  _user_home=$(getent passwd $username | cut -d: -f6)
  [ -z "$_user_home" ] || [ "$_user_home" = "/" ] && {
    log_warn "user home is unset"
    return 1
  }
  _ssh_prepare_ssh_conf $_user_home $username
  local _original_pwd=$PWD
  cd /tmp
  if [ -n "$system" ]; then
    log_warn "$username is a system user, bypassing configuration"
  else
    local ohome=$HOME
    export backup_ssh=1
    export optn_git_mirror=$optn_git_mirror
    export http_proxy="$http_proxy"
    export https_proxy="$https_proxy"
    export sudo_user=$username
    export warn_on_error=1
    export HOME=$_user_home
    export sudo_options="--preserve-env=optn_git_mirror,backup_ssh,http_proxy,https_proxy,sudo_user,warn_on_error,HOME -H"
    exec_wrap sudo_run conf restore || _user_configure_debug
    HOME=$ohome
  fi
  [ "$username" != "root" ] && {
    sudo_run chown -R $username:$username $_user_home
  }
  cd $_original_pwd
  unset _user_home _original_pwd
}
_user_configure_debug() {
  log_warn "error restoring configuration for $username"
  cat $_user_home/.ssh/id_*.pub
  cat $_user_home/.ssh/authorized_keys
  cat $_user_home/.ssh/config
}
_utils_get_feature_name() {
  local _path=$1
  case $_path in
  *feature*)
    printf '%s' "$_path" | sed \
      -e 's/^.*\/feature\///' \
      -e 's/.feature\/.*//' \
      -e 's/^/./' \
      -e 's/\//./g'
    ;;
  *)
    printf ''
    ;;
  esac
  unset _path
}
_utils_portage_install_file() {
  local _portage_type=$1
  local _file=$2
  sudo_run mkdir -p /etc/portage/$_portage_type
  sudo_run cp $_file /etc/portage/$_portage_type/app.$target_application_name$(_utils_get_feature_name $_file)
  unset _portage_type _file
}
_utils_portage_uninstall_file() {
  local _portage_type=$1
  local _file=$2
  sudo_run rm -f /etc/portage/$_portage_type/app.$target_application_name$(_utils_get_feature_name $_file)
  unset _portage_type _file
}
_utils_portage_is_installed() {
  local _portage_type=$1
  local _file=$2
  [ -e /etc/portage/$_portage_type/app.$target_application_name$(_utils_get_feature_name $_file) ]
  unset _portage_type _file
}
_requires_reboot() {
  package_${linux_package_manager}_requires_reboot
}
_package_install_do() {
  package_${linux_package_manager}_install_do "$@"
}
_package_uninstall_do() {
  package_${linux_package_manager}_uninstall_do "$@"
}
_package_is_installed() {
  package_${linux_package_manager}_is_installed "$@"
}
package_bootstrap() {
  package_${linux_package_manager}_bootstrap "$@"
}
package_update() {
  log_detail "updating packages via ${linux_package_manager}"
  package_${linux_package_manager}_update "$@"
}
package_pacman_requires_reboot() {
  local datestamp=$(date +%Y-%m-%d)
  $GNU_GREP -Pcqm1 \
    "\[${datestamp}T[\d]{2}:[\\d]{2}:[\\d]{2}-[\\d]{4}\] \[ALPM\] upgraded ($conf_system_maintenance_reboot_packages)" \
    /var/log/pacman.log
}
package_pacman_install_do() {
  pacman_flags="-Sqyu --noconfirm --noprogressbar"
  _pacman_cmd "$@"
  local status=$?
  unset pacman_flags
  return $status
}
package_pacman_uninstall_do() {
  pacman_flags="-Rs --noconfirm --noprogressbar"
  _pacman_cmd "$@"
  local status=$?
  unset pacman_flags
  return $status
}
package_pacman_is_installed() {
  pacman_flags="-Q"
  sudo_not_required=1
  _pacman_cmd "$@"
  local status=$?
  unset pacman_flags sudo_not_required
  return $status
}
package_pacman_bootstrap() {
  _pacman_setup_keys
}
package_pacman_update() {
  pacman_flags="-Syuq --noconfirm --noprogressbar"
  _pacman_cmd "$@"
  unset pacman_flags
  aur_package_update
}
_pacman_cmd() {
  local log_target=/dev/null
  [ -n "$log_logfile" ] && log_target=$log_logfile
  local sudo_prefix=sudo_run
  [ -n "$sudo_not_required" ] && unset sudo_prefix
  [ "$APP_PLATFORM_ROOT" = "/" ] && {
    $sudo_prefix pacman $pacman_flags "$@" >>$log_target 2>&1
    return
  }
  [ "$_container_type" = "incus" ] && {
    log_warn "detected incus container, using incus exec"
    sudo_run incus exec $_container_name -- pacman $pacman_flags "$@" >>$log_target 2>&1
    return
  }
  $sudo_prefix pacman $pacman_flags --sysroot $APP_PLATFORM_ROOT "$@" >>$log_target 2>&1
}
_pacman_setup_keys() {
  [ -e $APP_PLATFORM_ROOT/etc/pacman.d/gnupg ] && {
    log_debug "pacman keys already initialized"
    return
  }
  sudo_run mkdir -p $APP_PLATFORM_ROOT/etc/pacman.d/gnupg
  sudo_run pacman-key --init
  sudo_run pacman-key --populate archlinux cachyos
}
pacman_package_bootstrap_is_package_available() {
  return 0
}
_emerge_portage_use_git() {
  [ -e $APP_PLATFORM_ROOT/etc/portage/repos.conf/gentoo.conf ] && return
  _emerge_portage_setup_gentoo_git_workspace_conf
  [ -e $APP_PLATFORM_ROOT/var/db/repos/gentoo/.git ] && {
    log_detail "gentoo workspace already exists"
    return
  }
  _emerge_portage_setup_gentoo_git_workspace
}
_emerge_portage_setup_gentoo_git_workspace_conf() {
  rm -rf $APP_PLATFORM_ROOT/etc/portage/repos.conf && mkdir -p $APP_PLATFORM_ROOT/etc/portage/repos.conf
  printf '
  [DEFAULT]
  main-repo = gentoo
  [gentoo]
  location = /var/db/repos/gentoo
  sync-type = git
  sync-uri = https://github.com/gentoo-mirror/gentoo.git
  auto-sync = yes
  sync-git-verify-commit-signature = yes
  sync-openpgp-key-path = /usr/share/openpgp-keys/gentoo-release.asc
  ' >$APP_PLATFORM_ROOT/etc/portage/repos.conf/gentoo.conf
}
_emerge_portage_setup_gentoo_git_workspace() {
  log_detail "cleaning $APP_PLATFORM_ROOT/var/db/repos/gentoo"
  rm -rf $APP_PLATFORM_ROOT/var/db/repos/gentoo/*
  log_warn "cloning gentoo repo @ /var/db/repos/gentoo"
  git clone --depth 1 https://github.com/gentoo-mirror/gentoo.git $APP_PLATFORM_ROOT/var/db/repos/gentoo
  log_warn "cloned gentoo repo @ /var/db/repos/gentoo"
}
_emerge_portage_mirrors() {
  [ "$APP_PLATFORM_ROOT" = "/" ] && return
  [ ! -e /etc/portage/make.conf ] && return
  grep -qm1 '^GENTOO_MIRRORS=.*$' /etc/portage/make.conf || return
  grep -qm1 '^GENTOO_MIRRORS=.*$' $APP_PLATFORM_ROOT/etc/portage/make.conf && return
  printf '# mirror from host\n' >>$APP_PLATFORM_ROOT/etc/portage/make.conf
  grep '^GENTOO_MIRRORS=.*$' /etc/portage/make.conf >>$APP_PLATFORM_ROOT/etc/portage/make.conf
}
_emerge_portage_package_accept_keywords() {
  [ -e $APP_PLATFORM_ROOT/etc/portage/package.accept_keywords/platform ] && return
  sudo_run mkdir -p $APP_PLATFORM_ROOT/etc/portage/package.accept_keywords /etc/portage/package.accept_keywords
  printf '%s\n' "$emerge_PLATFORM_PACKAGES_accept_keywords" >>$APP_PLATFORM_ROOT/etc/portage/package.accept_keywords/platform
  printf "$emerge_PLATFORM_PACKAGES_accept_keywords" >>/etc/portage/package.accept_keywords/platform
}
_emerge_portage_sync() {
  [ -n "$emerge_bootstrap_install" ] && return 1
  emerge_sync_file=$APP_PLATFORM_ROOT/var/cache/.portage.sync.time
  _emerge_portage_synced && {
    log_debug "portage was already synced today"
    return
  }
  mkdir -p $(dirname $emerge_sync_file)
  _package_emerge_cmd $emerge_options --sync && {
    date +%s >"$emerge_sync_file"
  }
}
_emerge_portage_synced() {
  [ ! -e $emerge_sync_file ] && return 1
  local last_synced=$(head -1 $emerge_sync_file)
  local current_time=$(date +%s)
  [ -z "$last_synced" ] && return 1
  [ $(($current_time - $last_synced)) -le $emerge_portage_refresh_period ]
}
service_install() {
  _install_filter_file_callback $1 _systemctl_enable
}
_systemctl_enable() {
  sudo_run systemctl enable --now "$@"
}
service_uninstall() {
  _install_filter_file_callback $1 _systemctl_disable
}
_systemctl_disable() {
  sudo_run systemctl disable --now "$@"
}
_download_fetch() {
  mkdir -p "$TARGET_APP_PLATFORM_CACHE_PATH"
  local _cached_filename
  if [ $# -gt 1 ]; then
    _cached_filename="$2"
  else
    _cached_filename=$(basename "$1" | sed -e 's/?.*$//')
  fi
  download_file="$TARGET_APP_PLATFORM_CACHE_PATH/$_cached_filename"
  [ -z "$no_cache" ] && {
    [ -e "$download_file" ] && {
      log_detail "$1 already downloaded to: $download_file"
      return
    }
  }
  if [ -z "$download_disabled" ]; then
    log_info "downloading $1 -> $download_file"
    curl $curl_flags -o "$download_file" -sL "$1"
  else
    _stdin_continue_if "Please manually download: $1 and place it in $download_file" "Y/n"
  fi
}
_download_install_file() {
  warn_on_error=1 validation_require "$1" "1 (_download_install_file) target filename" || return 1
  warn_on_error=1 validation_require "$download_file" "download_file" || return 1
  : ${_install_file_chmod:=444}
  log_info "installing $download_file -> $1"
  if [ "${INSTALL_TARGET:-USER}" = "SYSTEM" ]; then
    sudo_run mkdir -p $(dirname $1)
    sudo_run cp "$download_file" $1
    sudo_run chmod $_install_file_chmod $1
  else
    mkdir -p $(dirname $1)
    cp "$download_file" $1
    chmod $_install_file_chmod $1
  fi
  unset download_file
  [ -e $1 ] || {
    log_warn "failed to install file to: $1"
    return 1
  }
  _install_record_path "$1"
}
_ssh_prepare_ssh_conf() {
  local _path=$1
  local _user=$2
  sudo_run mkdir -p "$_path/.ssh/socket"
  sudo_run chmod 700 "$_path/.ssh/socket"
  printf 'StrictHostKeyChecking no\n' >>"$_path/.ssh/config"
  _ssh_init_bastion_host "$_path"
  [ "$_user" = "root" ] && return
  if [ -e /root/.ssh ]; then
    log_info "copying host ssh -> $_path/.ssh"
    sudo_run cp /root/.ssh/id* /root/.ssh/config /root/.ssh/known_hosts "$_path/.ssh"
  fi
  if [ -e /root/.config/walterjwhite/shell ]; then
    log_info "copying walterjwhite conf -> $_path/.config/walterjwhite/shell"
    sudo_run rm -rf "$_path/.config/walterjwhite/shell" && sudo_run mkdir -p "$_path/.config/walterjwhite"
    sudo_run cp -r /root/.config/walterjwhite/shell "$_path/.config/walterjwhite/shell"
  else
    log_warn "no walterjwhite conf found"
    find /tmp -maxdepth 1
  fi
  sudo_run chown -R "$_user:$_user" "$_path"
}
_ssh_init_bastion_host() {
  local _path=$1
  [ -z "$bastion_host" ] && return 1
  log_info "setting up SSH Bastion host: $_path"
  _ssh_bastion_host "$_path"
  _ssh_bastion_proxies "$_path"
  chmod 600 "$_path/.ssh/config"
}
_ssh_bastion_host() {
  local _path=$1
  log_info "setting up SSH Bastion host: $_path"
  printf 'Host host-proxy\n' >>"$_path/.ssh/config"
  printf ' Hostname %s\n' "$bastion_host" >>"$_path/.ssh/config"
  printf ' User root\n' >>"$_path/.ssh/config"
}
_ssh_bastion_proxies() {
  local _path=$1
  for bastion_hostname in $(printf '%s' "$bastion_hostnames" | sort -u); do
    _ssh_bastion_proxy "$_path"
  done
}
_ssh_bastion_proxy() {
  local _path=$1
  log_info "setting up SSH host proxy: $_path"
  printf 'Host %s\n' "$bastion_hostname" >>"$_path/.ssh/config"
  printf ' ProxyJump host-proxy:%s\n' "$bastion_port" >>"$_path/.ssh/config"
  printf ' User root\n' >>"$_path/.ssh/config"
}
_ssh_use_host_ssh_conf() {
  rm -rf "$target/tmp/HOST-SSH" && mkdir -p "$target/tmp"
  cp -R /root/.ssh "$target/tmp/HOST-SSH"
}
_zfs_rclone() {
  local rclone_patch_path=patches/zfs-rclone.patch/package
  mkdir -p $(dirname $rclone_patch_path)
  if [ -n "$_ZFS_RCLONE_TARGET" ]; then
    log_info "configuring ZFS rclone target: $_ZFS_RCLONE_TARGET on $_zfs_volume"
    [ ! -e $rclone_patch_path ] && printf 'net-misc/rclone\n' >>$rclone_patch_path
    zfs set rclone:target=$_ZFS_RCLONE_TARGET $_zfs_volume
  fi
  [ -n "$_ZFS_RCLONE_PATH" ] && zfs set rclone:path=$_ZFS_RCLONE_PATH $_zfs_volume
  unset _ZFS_RCLONE_PATH _ZFS_RCLONE_TARGET
}
_zfs_zap() {
  local zap_patch_path=patches/zfs-zap.patch/zap.post-run
  mkdir -p $(dirname $zap_patch_path)
  if [ -n "$_ZFS_ZAP_SNAP" ]; then
    log_warn "detected ZFS ZAP, setting up zap"
    zfs set zap:snap=on $_zfs_volume
  fi
  [ -n "$_ZFS_ZAP_TTL" ] && zfs set zap:ttl=$_ZFS_ZAP_TTL $_zfs_volume
  [ -n "$_ZFS_ZAP_BACKUP" ] && zfs set zap:backup=$_ZFS_ZAP_BACKUP $_zfs_volume
  unset _ZFS_ZAP_TTL _ZFS_ZAP_BACKUP _ZFS_ZAP_SNAP
}
readonly APPLICATION_NAME=os-installer
readonly APPLICATION_START_TIME=$(date +%s)
readonly APPLICATION_CMD=$(basename $0)
readonly APP_PLATFORM_ARCHITECTURE=$(uname -m)
readonly APP_PLATFORM_OS_NAME=$(uname)
case "$APP_PLATFORM_OS_NAME" in
Darwin)
  readonly APP_PLATFORM_PLATFORM="Apple"
  ;;
MINGW64_NT-* | MSYS_NT-*)
  readonly APP_PLATFORM_PLATFORM="Windows"
  ;;
*)
  readonly APP_PLATFORM_PLATFORM="$APP_PLATFORM_OS_NAME"
  ;;
esac
: ${APP_PLATFORM_ROOT:=/}
APP_PLATFORM_ROOT=$(realpath -m $APP_PLATFORM_ROOT)
[ "$HOME" = "/" ] || [ -z "$HOME" ] && HOME=/root
readonly RUN_PATH=/tmp/$USER/walterjwhite/app
readonly APP_CONTEXT="default"
readonly APPLICATION_CONTEXT_GROUP=$RUN_PATH/$APP_CONTEXT
readonly APPLICATION_CMD_DIR=$APPLICATION_CONTEXT_GROUP/$APPLICATION_NAME/$APPLICATION_CMD
readonly APPLICATION_PIPE=$APPLICATION_CMD_DIR/$$
readonly APPLICATION_PIPE_DIR=$(dirname $APPLICATION_PIPE)
case $0 in
*${HOME}*)
  readonly APP_PLATFORM_PATH=$(printf '%s' "$APP_PLATFORM_ROOT/$HOME/.local/walterjwhite" | tr -s /)
  readonly APP_PLATFORM_CONFIG_PATH=$(printf '%s' $APP_PLATFORM_ROOT${HOME}/.config/walterjwhite/shell | tr -s /)
  readonly APP_PLATFORM_BIN_PATH=$(printf '%s' $APP_PLATFORM_ROOT${HOME}/.local/bin | tr -s /)
  ;;
*)
  readonly APP_PLATFORM_PATH=$(printf '%s' "$APP_PLATFORM_ROOT/usr/local/walterjwhite" | tr -s /)
  readonly APP_PLATFORM_CONFIG_PATH=$(printf '%s' $APP_PLATFORM_ROOT/usr/local/etc/walterjwhite/shell | tr -s /)
  readonly APP_PLATFORM_BIN_PATH=$(printf '%s' $APP_PLATFORM_ROOT/usr/local/bin | tr -s /)
  ;;
esac
readonly DATA_PATH=$(printf '%s' ${APP_PLATFORM_ROOT}$HOME/.data | tr -s /)
readonly APP_PLATFORM_DATA_PATH=$DATA_PATH
readonly APP_DATA_PATH=$APP_PLATFORM_DATA_PATH/$APPLICATION_NAME
readonly APP_PATH=$APP_PLATFORM_PATH/apps/$APPLICATION_NAME
readonly APP_CONFIG_PATH=$APP_PLATFORM_CONFIG_PATH/$APPLICATION_NAME
readonly EXTENSIONS_PATH=$APP_PLATFORM_PATH/extensions
readonly GNU_GREP=grep
readonly GNU_SED=sed
readonly _TAR_ARGS=" -f - "
readonly _SUDO_CMD="sudo"
readonly EMERGE_FLAGS="-q --quiet-build --quiet-fail"
readonly IO_STAT_ARGS='-c %a'
readonly APP_PLATFORM_SUB_PLATFORM=$($GNU_GREP -Ph "^NAME=" $APP_PLATFORM_ROOT/etc/os-release 2>/dev/null | sed -e 's/^NAME=//' -e 's/ Linux//' -e 's/"//g')
case $APP_PLATFORM_SUB_PLATFORM in
Arch | CachyOS)
  linux_package_manager=pacman
  case $APP_PLATFORM_SUB_PLATFORM in
  CachyOS)
    readonly APP_PLATFORM_DERIVED_SUB_PLATFORM=Arch
    ;;
  esac
  readonly PLATFORM_PACKAGES="bc beep curl expect git shellcheck sudo shfmt"
  readonly NPM_PACKAGE="npm"
  readonly RUST_PACKAGE="rust"
  readonly PYPI_PACKAGE="python"
  readonly GO_PACKAGE="go gcc"
  readonly EXPECT_PACKAGE="expect"
  conf_system_maintenance_reboot_packages="linux-cachyos-lts-zfs|linux-cachyos-zfs|linux-cachyos|linux-cachyos-lts|linux-firmware"
  ;;
Gentoo)
  linux_package_manager=emerge
  readonly PLATFORM_PACKAGES="dev-vcs/git dev-tcltk/expect net-misc/curl dev-util/sh app-admin/sudo app-misc/beep app-portage/gentoolkit"
  readonly PLATFORM_PACKAGES_ACCEPT_KEYWORDS="dev-util/sh ~amd64"
  readonly NPM_PACKAGE="net-libs/nodejs"
  readonly RUST_PACKAGE="dev-lang/rust"
  readonly PYPI_PACKAGE="dev-lang/python"
  readonly GO_PACKAGE="dev-lang/go"
  readonly EXPECT_PACKAGE="dev-tcltk/expect"
  conf_system_maintenance_reboot_packages="gentoo-kernel"
  ;;
esac
_metadata_load
_include_optional . beep context git init logging net os-installer paths platform wait
: ${beep_enabled:=0}
: ${conf_log_beep_timeout:=5}
: ${conf_log_beep_err:='-f 1000 -l 1000'}
: ${conf_log_beep_alrt:='-f 1000 -l 100 -n -f 1000 -l 100'}
: ${conf_log_beep_scs:='-f 1600 -l 100'}
: ${conf_log_beep_wrn:='-f 1500 -l 100 -n -f 1000'}
: ${conf_log_beep_info:=''}
: ${conf_log_beep_detail:=''}
: ${conf_log_beep_debug:=''}
: ${conf_log_beep_stdin:='-f 1000 -l 100 -n -f 1400'}
: ${conf_log_sudo_beep_tone:='-f 1000 -l 100 -n -f 1400 -l 50 -n -f 1200'}
: ${APP_CONTEXT:=$_CONSOLE_CONTEXT_ID}
: ${APP_CONTEXT:=default}
CONF_LOG_HEADER="##################################################"
: ${conf_log_c_err:="1;31"}
: ${conf_log_c_scs:="1;32"}
: ${conf_log_c_wrn:="1;33"}
: ${conf_log_c_info:="1;36"}
: ${conf_log_c_detail:="1;0;36"}
: ${conf_log_c_debug:="1;35"}
: ${conf_log_c_stdin:="1;34"}
: ${conf_log_date_format:="%y/%m/%d|%h:%m:%s"}
: ${conf_log_date_time_format:="%y/%m/%d %h:%m:%s"}
: ${conf_log_level:=2}
: ${console_log_fd:=2}
: ${conf_log_indent:="  "}
: ${conf_log_validation_function:=warn}
: ${conf_log_waiter_level:=debug}
: ${conf_log_feature_timeout_error_level:=warn}
: ${conf_log_long_running_cmd:=30}
: ${conf_log_long_running_cmd_lines:=1000}
: ${conf_log_date_time_to_console:=0}
command -v mail >/dev/null 2>&1 || conf_log_mail_disabled=1
[ -n "${GITHUB_ACTIONS}" ] || [ -n "${CI}" ] && {
  NON_INTERACTIVE=1
  NO_LOG_FILE=1
}
: ${conf_network_test_timeout:=5}
: ${conf_network_test_targets:="http://connectivity-check.ubuntu.com http://example.org http://www.google.com http://telehack.com http://lxer.com"}
: ${curl_flags:="--connect-timeout 5 --max-time 30"}
: ${emerge_portage_refresh_period:=3600}
: ${pacman_refresh_period:=3600}
: ${pacman_bootstrap_install:=}
: ${conf_wait_interval:=30}
os_installer_instance=$(date +%s)
log_logfile=/var/log/walterjwhite/os-installer-$os_installer_instance.log
: ${conf_os_installer_ssh_key_type:=ed25519}
: ${conf_os_installer_disk_type:=ZFS}
: ${conf_os_installer_mountpoint:=/mnt/os}
: ${conf_os_installer_execution_log:="/tmp/.os/exec"}
: ${conf_os_installer_system_workspace:="/tmp/os"}
: ${os_installer_drive_mount_point:=/mnt/usb}
: ${os_installer_system_timezone:=America/New_York}
: ${os_installer_configuration_branch:=main}
: ${os_installer_cache_enabled:=1}
: ${os_installer_cache:=cache}
: ${os_installer_cache_path:=/cache}
case $APPLICATION_CMD in
*os-installer* | *chroot* | jail-setup)
  ;;
*)
  unset log_logfile
  ;;
esac
: ${os_installer_zap_snapshot_retention_duration:=30d}
conf_os_installer_cachyos_live_iso_repository_url="https://github.com/CachyOS/CachyOS-Live-ISO"
: ${_MODULES_IMPLEMENTATION:=host}
linux_package_manager=pacman
distribution_function_name=arch
os_installer_disk_dev_encrypted_partition_id=2
: ${os_installer_stage3_type:="hardened-systemd"}
: ${os_installer_kernel:=gentoo-kernel}
: ${os_installer_init:=dracut}
: ${os_installer_boot_loader:=efibootmgr}
: ${os_installer_boot_method:=uefi}
: ${os_installer_boot_fs:=zpool}
: ${os_installer_boot_loader:=efibootmgr}
: ${conf_cron_provider:=systemd}
: ${os_installer_syslog:=sysklogd}
: ${os_installer_syslog_use:=logrotate}
: ${os_installer_indexing:=plocate}
: ${os_installer_l10n:="en en-US"}
: ${os_installer_luks_cipher:=aes-xts-plain}
: ${os_installer_luks_key_size:=512}
: ${os_installer_luks_hash:=sha512}
: ${os_installer_software_license:="@FREE @BINARY-REDISTRIBUTABLE"}
: ${os_installer_time_synchronization:=timedatectl}
: ${os_installer_kernel:=gentoo-kernel}
: ${os_installer_kernel_cmdline_args:="consoleblank=300 quiet"}
: ${os_installer_system_locale_eselect:=en_US.utf8}
: ${os_installer_system_locale_gen:=en_US ISO-8859-1|en_US.UTF-8 UTF-8}
: ${os_installer_portage_niceness=19}
: ${os_installer_portage_scheduling_policy=batch}
: ${conf_os_installer_cups_conf_dir:=/etc/cups}
: ${conf_os_installer_package_install_once:=1}
_ZPOOL_OPTIONS="-o ashift=12 -o autotrim=on -O acltype=posixacl -O xattr=sa -O relatime=on -O compression=zstd -m none"
os_installer_umount_options="l"
: ${conf_os_installer_init:="systemd"}
: ${_OS_CONTAINER_MOUNTPOINT:=/containers}
: ${os_installer_cache_fses:=var/cache/distfiles}
: ${os_installer_sshfs_type:=fuse.sshfs}
: ${os_installer_sshfs_options:="-o allow_other"}
case $APPLICATION_CMD in
os-installer-configure)
  case $APP_PLATFORM_SUB_PLATFORM in
  CachyOS | Arch)
    conf_os_installer_disk_dev_name=zpcachyos
    ;;
  esac
  ;;
esac
: ${conf_git_system_template_path:=/usr/share/git/templates}
: ${conf_git_clone_timeout:=30}
: ${conf_git_compression_format:=xz}
: ${conf_git_compression_cmd:="xz -z"}
: ${conf_git_squash_commits:=2}
: ${conf_git_backup_date_time_format:=%Y.%m.%d-%H.%M.%S}
: ${conf_git_delete_period_IN_DAYS:=365}
: ${conf_git_delete_dryrun:=0}
: ${conf_git_workspace_base_path:=$HOME/workspace}
: ${conf_git_workspace_base_branch:=dev}
readonly GIT_PROJECT_BASE_PATH=$HOME/projects
readonly GIT_WORKSPACE_BASE_PATH=$conf_git_workspace_base_path
#
#
: ${no_remove_unused_functions:=}
: ${no_remove_unused_variables:=}
#
#
#
#
: ${remove_unused_variables_exclude_patterns:=}
: ${no_check_missing_functions:=}
trap '_exit_on_hup $LINENO' 1
trap '_exit_on_int $LINENO' 2
trap '_exit_on_quit $LINENO' 3
trap '_exit_on_illegal $LINENO' 4
trap '_exit_on_abort $LINENO' 6
trap '_exit_on_alarm $LINENO' 14
trap '_exit_on_term $LINENO' 15
trap exit_with_success 0
_processes_is_backgrounded && backgrounded=1
[ -n "$NON_INTERACTIVE" ] && {
  [ -z "$NO_LOG_FILE" ] && {
    [ -z "$log_logfile" ] && log_logfile="$APP_DATA_PATH/log/$(date +%Y%m%d-%H%M%S).log"
  }
}
log_init
for _ARG in "$@"; do
  case $_ARG in
  -h | --help)
    _help_print_and_exit
    ;;
  -w=*)
    wait_waiter_pid="${1#*=}"
    shift
    ;;
  -w)
    readonly WAIT_WAITEE=1
    shift
    ;;
  -conf-* | -[a-z0-9][a-z0-9][a-z0-9]*)
    _configuration_name=${_ARG#*-}
    _configuration_name=${_configuration_name%%=*}
    printf '%s' "$_configuration_name" | grep -cqm1 '_$' && {
      _configuration_name=${_configuration_name%%_*}
      printf '%s' "$_configuration_name" | grep -cqm1 '^conf' && {
        _configuration_name=$(printf '%s' "$_configuration_name" | sed -e "s/-/-$APPLICATION_NAME-/" -e 's/--/-/')
      } || {
        _configuration_name=$(printf '%s' "$_configuration_name" | sed -e "s/^/$APPLICATION_NAME-/" -e 's/--/-/')
      }
    }
    _configuration_name=$(printf '%s' $_configuration_name | tr '-' '_' | tr '[:upper:]' '[:lower:]')
    case "$_ARG" in
    *-*)
      _configuration_value=${_ARG#*=}
      ;;
    *)
      _configuration_value=1
      ;;
    esac
    eval "${_configuration_name}=\"$_configuration_value\""
    unset _configuration_name _configuration_value
    shift
    ;;
  --)
    shift
    break
    ;;
  *)
    break
    ;;
  esac
done
log_enable_debug_mode
readonly REQUIRED_APP_CONF="conf_install_go_path conf_os_installer_system_git"
_cfg_validate_required
wait_waitee_init
wait_waiter
log_add_context chroot
_chroot_init
_configure_configure
[ -z "$_in_container" ] && _start_ssh
_hostname_hostname
_chroot_timezone
_run_run _system_main
_original_log_file=$log_logfile
_patches_patches file
_system_patches
_run_parallel
_patches_patches package_uninstall package
_run_parallel_wait
_patches_patches group user
_patches_patches app go npm rust pypi
_patches_patches link
_patches_patches chown chmod run crontab
_patches_patches service fstab cups_printer
_patches_patches sysctl post_run
$_updatedb_cmd
_log_set_logfile $_original_log_file
if [ -z "$_in_container" ]; then
  _stop_ssh
fi
