#!/bin/sh
_github_latest_release() {
	curl -sL https://api.github.com/repos/$1/$2/releases/latest | jq -r ".tag_name"
}
_github_fetch_latest_artifact() {
	local _github_organization_name=$1
	local _github_repository_name=$2
	local _artifact_name=$3
	local _artifact_suffix=$4
	shift 4
	local _latest_version=$(_github_latest_release $_github_organization_name $_github_repository_name)
	[ -z "$git_artifact_url_function" ] && git_artifact_url_function=_github_artifact_url
	$git_artifact_url_function $_github_organization_name $_github_repository_name $_latest_version $_artifact_name $_artifact_suffix
	_download_fetch $git_github_artifact_url "$@"
	unset git_github_artifact_url
}
_github_artifact_url() {
	git_github_artifact_url=https://github.com/$1/$2/releases/download/${3}/${4}${3}${5}
}
_github_artifact_url_static() {
	git_github_artifact_url=https://github.com/$1/$2/releases/download/${3}/${4}
}
download_file=""
_download_fetch() {
	mkdir -p $APP_PLATFORM_CACHE_PATH
	local _cached_filename
	if [ $# -gt 1 ]; then
		_cached_filename="$2"
	else
		_cached_filename=$(basename $1 | sed -e 's/?.*$//')
	fi
	download_file=$APP_PLATFORM_CACHE_PATH/$_cached_filename
	[ -z "$no_cache" ] && {
		[ -e $download_file ] && {
			log_detail "$1 already downloaded to: $download_file"
			return
		}
	}
	if [ -z "$download_disabled" ]; then
		log_info "downloading $1 -> $download_file"
		curl $curl_options -o $download_file -s -L "$1"
	else
		_stdin_continue_if "Please manually download: $1 and place it in $download_file" "Y/n"
	fi
}
_download_install_file() {
	warn_on_error=1 validation_require "$1" "1 (_download_install_file) target filename" || return 1
	: ${_install_file_chmod:=444}
	log_info "installing $download_file -> $1"
	mkdir -p $(dirname $1)
	cp $download_file $1
	chmod $_install_file_chmod $1
	unset download_file
	[ -e $1 ] || log_warn "failed to install file to: $1"
}
_download_verify() {
	local _hash_algorithm
	_hash_algorithm=512
	shasum -a $_hash_algorithm -c $1 >/dev/null 2>&1
}
: ${conf_dev_java_timo_a_lomboker_jdk:=java}
: ${conf_dev_java_timo_a_lomboker_version:=0.0.0}
: ${conf_dev_java_timo_a_lomboker_jar_NAME:=lomboker-$conf_dev_java_timo_a_lomboker_version.jar}
: ${conf_dev_java_timo_a_lomboker_jar:=/usr/local/walterjwhite/programming-languages/tools/$conf_dev_java_timo_a_lomboker_jar_NAME}
_get_installed_timo_a_lomboker_version() {
  [ -e /usr/local/walterjwhite/programming-languages/timo-a-lomboker.jar ] && java -jar /usr/local/walterjwhite/programming-languages/timo-a-lomboker.jar version | cut -d' ' -f2
}
_get_latest_timo_a_lomboker_version() {
  _latest_timo_a_lomboker_version=$(_github_latest_release timo-a lomboker | sed -e 's/^v//')
}
_is_latest_timo_a_lomboker_installed() {
  local _installed_version=$(_get_installed_timo_a_lomboker_version)
  [ "$_installed_version" = "$_latest_timo_a_lomboker_version" ]
}
_install_timo_a_lomboker() {
  log_info "installing timo-a-lomboker Java JAR"
  _download_fetch https://github.com/timo-a/lomboker/releases/download/v${_latest_timo_a_lomboker_version}/lomboker-${_latest_timo_a_lomboker_version}.jar
  _download_install_file /usr/local/walterjwhite/programming-languages/timo-a-lomboker.jar
}
_get_latest_timo_a_lomboker_version
if ! _is_latest_timo_a_lomboker_installed; then
  _install_timo_a_lomboker
fi
