#!/bin/sh
_extract_extract() {
  if [ $# -lt 2 ]; then
    log_warn "expecting 2 arguments, source file, and target to extract to"
    return 1
  fi
  log_info "extracting $1"
  [ -n "$clean" ] && {
    rm -rf $2
    mkdir -p $2
  }
  case $1 in
  *.tar.gz | *.tgz | *.tar.bz2 | *.tbz2 | *.tar.xz)
    tar xf $1 -C $2
    ;;
  *.zip)
    unzip -q $1 -d $2
    ;;
  *)
    log_warn "extension unsupported - $1"
    return 2
    ;;
  esac
}
_github_latest_release() {
  [ -z "$4" ] && {
    get_latest_${1}_version
    return
  }
  local _field=${4#.}
  curl $curl_flags -sL https://api.github.com/repos/$2/$3/releases/latest | grep -m1 "\"$_field\"" | sed 's/.*"[^"]*": *"\([^"]*\)".*/\1/'
}
_github_fetch() {
  local download_url=$(curl $curl_flags -s https://api.github.com/repos/$1/$2/releases/latest | jq -r "$3")
  [ -z "$download_url" ] && {
    log_warn "no matching artifact found"
    return 1
  }
  _download_fetch "$download_url" $4-$5
}
_github_install_latest() {
  local function_name=$(printf '%s' $1 | tr '-' '_')
  local latest_version=$(_github_latest_release "$function_name" "$2" "$3" "$4")
  local installed_version=$(get_installed_${function_name}_version)
  [ "$installed_version" = "$latest_version" ] && {
    log_detail "$1 is already installed and up-to-date"
    return
  }
  if [ -z "$installed_version" ]; then
    log_detail "installing $1"
  else
    log_detail "updating $1"
  fi
  _github_fetch "$2" "$3" "$5" "$6" "$latest_version" || return
  [ -z "$7" ] && {
    log_info "calling install_$function_name"
    install_$function_name
    return
  }
  _install_file_chmod=755 _download_install_file "$TARGET_APP_PLATFORM_BIN_PATH/$7"
}
_download_fetch() {
  mkdir -p "$TARGET_APP_PLATFORM_CACHE_PATH"
  local _cached_filename
  if [ $# -gt 1 ]; then
    _cached_filename="$2"
  else
    _cached_filename=$(basename "$1" | sed -e 's/?.*$//')
  fi
  download_file="$TARGET_APP_PLATFORM_CACHE_PATH/$_cached_filename"
  [ -z "$no_cache" ] && {
    [ -e "$download_file" ] && {
      log_detail "$1 already downloaded to: $download_file"
      return
    }
  }
  if [ -z "$download_disabled" ]; then
    log_info "downloading $1 -> $download_file"
    curl $curl_flags -o "$download_file" -sL "$1"
  else
    _stdin_continue_if "Please manually download: $1 and place it in $download_file" "Y/n"
  fi
}
_download_install_file() {
  warn_on_error=1 validation_require "$1" "1 (_download_install_file) target filename" || return 1
  warn_on_error=1 validation_require "$download_file" "download_file" || return 1
  : ${_install_file_chmod:=444}
  log_info "installing $download_file -> $1"
  if [ "${INSTALL_TARGET:-USER}" = "SYSTEM" ]; then
    sudo_run mkdir -p $(dirname $1)
    sudo_run cp "$download_file" $1
    sudo_run chmod $_install_file_chmod $1
  else
    mkdir -p $(dirname $1)
    cp "$download_file" $1
    chmod $_install_file_chmod $1
  fi
  unset download_file
  [ -e $1 ] || {
    log_warn "failed to install file to: $1"
    return 1
  }
  _install_record_path "$1"
}
_download_verify() {
  shasum -a 512 -c $1 >/dev/null 2>&1
}
get_installed_trivy_version() {
  command -v trivy > /dev/null 2>&1 || return
  printf 'v'
  trivy --version | $GNU_GREP -Po 'Version: \K[0-9]+\.[0-9]+\.[0-9]+'
}
install_trivy() {
  mkdir /tmp/trivy
  _extract_extract $download_file /tmp/trivy
  mv /tmp/trivy/trivy $TARGET_APP_PLATFORM_BIN_PATH
  rm -rf /tmp/trivy
}
_github_install_latest trivy aquasecurity trivy '.tag_name' \
    ".assets[] | select(.name | test(\"trivy_.*.FreeBSD-64bit.tar.gz\")) | .browser_download_url" \
    trivy-FreeBSD-64bit.tar.gz
