#!/bin/sh
_extract_extract() {
  if [ $# -lt 2 ]; then
    log_warn "expecting 2 arguments, source file, and target to extract to"
    return 1
  fi
  log_info "extracting $1"
  [ -n "$clean" ] && {
    rm -rf $2
    mkdir -p $2
  }
  case $1 in
  *.tar.gz | *.tgz | *.tar.bz2 | *.tbz2 | *.tar.xz)
    tar xf $1 -C $2
    ;;
  *.zip)
    unzip -q $1 -d $2
    ;;
  *)
    log_warn "extension unsupported - $1"
    return 2
    ;;
  esac
}
_download_fetch() {
  mkdir -p "$TARGET_APP_PLATFORM_CACHE_PATH"
  local _cached_filename
  if [ $# -gt 1 ]; then
    _cached_filename="$2"
  else
    _cached_filename=$(basename "$1" | sed -e 's/?.*$//')
  fi
  download_file="$TARGET_APP_PLATFORM_CACHE_PATH/$_cached_filename"
  [ -z "$no_cache" ] && {
    [ -s "$download_file" ] && {
      log_detail "$1 already downloaded to: $download_file"
      return
    }
  }
  if [ -z "$download_disabled" ]; then
    log_info "downloading $1 -> $download_file"
    curl $conf_curl_flags -f -o "$download_file" -sL "$1"
    local _curl_status=$?
    if [ "$_curl_status" -ne 0 ]; then
      rm -f "$download_file"
      log_warn "failed to download ($_curl_status): $1"
      return $_curl_status
    fi
  else
    _stdin_continue_if "Please manually download: $1 and place it in $download_file" "Y/n"
  fi
}
_download_install_file() {
  warn_on_error=1 validation_require "$1" "1 (_download_install_file) target filename" || return 1
  warn_on_error=1 validation_require "$download_file" "download_file" || return 1
  : ${_install_file_chmod:=444}
  log_info "installing $download_file -> $1"
  if [ "${INSTALL_TARGET:-USER}" = "SYSTEM" ]; then
    sudo_run mkdir -p $(dirname $1)
    sudo_run cp "$download_file" $1
    sudo_run chmod $_install_file_chmod $1
  else
    mkdir -p $(dirname $1)
    cp "$download_file" $1
    chmod $_install_file_chmod $1
  fi
  unset download_file
  [ -e $1 ] || {
    log_warn "failed to install file to: $1"
    return 1
  }
  _install_record_path "$1"
}
_download_verify() {
  shasum -a 512 -c $1 >/dev/null 2>&1
}
git_town_version=23.0.3
_get_installed_git_town_version() {
    if [ -e $TARGET_APP_PLATFORM_BIN_PATH/git-town ]; then
        $TARGET_APP_PLATFORM_BIN_PATH/git-town version | awk '{print $NF}'
    fi
}
_install_git_town() {
  _download_fetch "https://github.com/git-town/git-town/releases/download/v${git_town_version}/git-town_linux_intel_64.tar.gz"
    tmp_dir=$(_mktemp_options=d _mktemp_mktemp)
    exit_defer rm -rf "$tmp_dir"
    _extract_extract $download_file $tmp_dir
    mv $tmp_dir/git-town $TARGET_APP_PLATFORM_BIN_PATH/git-town
    chmod +x $TARGET_APP_PLATFORM_BIN_PATH/git-town
}
case $APP_PLATFORM_SUB_PLATFORM in
    Gentoo)
        installed_git_town_version=$(_get_installed_git_town_version)
        if [ "$installed_git_town_version" = "$git_town_version" ]; then
            log_detail "git-town $git_town_version is already installed"
        else
            _install_git_town
        fi
        ;;
esac
