#!/bin/sh
_extract_extract() {
  if [ $# -lt 2 ]; then
    log_warn "expecting 2 arguments, source file, and target to extract to"
    return 1
  fi
  log_info "extracting $1"
  [ -n "$clean" ] && {
    rm -rf $2
    mkdir -p $2
  }
  case $1 in
  *.tar.gz | *.tgz | *.tar.bz2 | *.tbz2 | *.tar.xz)
    tar xf $1 -C $2
    ;;
  *.zip)
    unzip -q $1 -d $2
    ;;
  *)
    log_warn "extension unsupported - $1"
    return 2
    ;;
  esac
}
_download_fetch() {
  mkdir -p "$TARGET_APP_PLATFORM_CACHE_PATH"
  local _cached_filename
  if [ $# -gt 1 ]; then
    _cached_filename="$2"
  else
    _cached_filename=$(basename "$1" | sed -e 's/?.*$//')
  fi
  download_file="$TARGET_APP_PLATFORM_CACHE_PATH/$_cached_filename"
  [ -z "$no_cache" ] && {
    [ -e "$download_file" ] && {
      log_detail "$1 already downloaded to: $download_file"
      return
    }
  }
  if [ -z "$download_disabled" ]; then
    log_info "downloading $1 -> $download_file"
    curl $conf_curl_flags -o "$download_file" -sL "$1"
  else
    _stdin_continue_if "Please manually download: $1 and place it in $download_file" "Y/n"
  fi
}
_download_install_file() {
  warn_on_error=1 validation_require "$1" "1 (_download_install_file) target filename" || return 1
  warn_on_error=1 validation_require "$download_file" "download_file" || return 1
  : ${_install_file_chmod:=444}
  log_info "installing $download_file -> $1"
  if [ "${INSTALL_TARGET:-USER}" = "SYSTEM" ]; then
    sudo_run mkdir -p $(dirname $1)
    sudo_run cp "$download_file" $1
    sudo_run chmod $_install_file_chmod $1
  else
    mkdir -p $(dirname $1)
    cp "$download_file" $1
    chmod $_install_file_chmod $1
  fi
  unset download_file
  [ -e $1 ] || {
    log_warn "failed to install file to: $1"
    return 1
  }
  _install_record_path "$1"
}
_download_verify() {
  shasum -a 512 -c $1 >/dev/null 2>&1
}
command -v ollama > /dev/null 2>&1 || {
    _download_fetch https://ollama.ai/download/Ollama-darwin.zip
    ollama_contents=$(_mktemp_options=d _mktemp_mktemp)
    _extract_extract $download_file $ollama_contents
    mv $ollama_contents/Ollama.app /Applications
    _install_record_dir "/Applications/Ollama.app"
    local _dest="$TARGET_APP_PLATFORM_BIN_PATH/ollama"
    ln -s /Applications/Ollama.app/Contents/Resources/ollama "$_dest"
    _install_record_symlink "$_dest"
    rm -rf $ollama_contents
}
