#!/bin/sh
: ${conf_dev_java_formatter:=google}
: ${suspend_jvm:=n}
: ${debug_port:=5005}
: ${conf_dev_commented_file_action:=delete}
commented_file_uncomment() {
	$GNU_SED -i 's/^\/\/ //' $_FILE
	$GNU_SED -i 's/^\/\/$//' $_FILE
	$GNU_SED -i 's/^\/\/\/\/ //' $_FILE
}
commented_file_delete() {
	rm -f $_FILE
}
